(()=>{'use strict';const all=[];const add=(id,label,desc,data)=>all.push({id,label,desc,data:{type:id,title:label+'｜合成範例',...data}});
add('priority_eisenhower','重要／緊急優先矩陣','先做、排程、委派、刪減',{points:[{title:'明天繳交的報告',x:90,y:90},{title:'下週概念複習',x:25,y:85},{title:'不重要的臨時請求',x:85,y:20},{title:'無目的瀏覽',x:20,y:15}]});
add('time_budget','每日時間預算','任務需求與每日可用時間比較',{available_minutes:240,tasks:[{title:'課程預習',minutes:60},{title:'解題',minutes:90},{title:'專題',minutes:60}],reserve_minutes:30});
add('priority_value_effort','價值／時間排序','以每分鐘價值分數比較任務',{tasks:[{title:'訂正錯題',value_score:9,minutes:30},{title:'美化筆記',value_score:4,minutes:60},{title:'確認報告要求',value_score:8,minutes:15}]});
add('pomodoro_planner','番茄鐘工時計畫','專注輪次與休息合計，不含最後一輪休息',{focus_minutes:25,rounds:6,short_break:5,long_break:15,long_every:4});
add('time_savings_roi','時間投資回收','建立工具花的時間與後續節省比較',{setup_minutes:120,saved_minutes_each:10,maintenance_minutes_each:2,uses:30});
add('meeting_person_hours','會議人時成本','每位參與者分鐘合計成人時',{participants:[{title:'主持人',minutes:45},{title:'組員 A',minutes:45},{title:'組員 B',minutes:30}],meeting_minutes:45});
add('deadline_backplan','期限倒排日曆','從截止日期向前分配每日工時',{deadline:'2026-10-16',daily_minutes:120,workdays:[0,1,2,3,4],excluded_dates:[],tasks:[{title:'資料整理',minutes:180},{title:'初稿',minutes:240},{title:'校對提交',minutes:60}]});
add('critical_path_plan','關鍵路徑 CPM','依前置任務算最早最晚開始與浮時',{tasks:[{id:'a',title:'需求確認',duration:2,depends:[]},{id:'b',title:'原型',duration:4,depends:['a']},{id:'c',title:'資料準備',duration:2,depends:['a']},{id:'d',title:'驗證',duration:3,depends:['b','c']}],unit:'天'});
add('time_variance_audit','計畫／實際時間差異','找出超時與低估的項目',{tasks:[{title:'閱讀',planned_minutes:60,actual_minutes:80},{title:'解題',planned_minutes:90,actual_minutes:100},{title:'報告',planned_minutes:60,actual_minutes:45}]});
add('little_law_time','Little 定律流程時間','平均在製量 ÷ 平均產出率',{average_wip:12,throughput_per_hour:3,unit:'件'});
window.VC_LEARNING_TEMPLATES.push(...all);CHARTS.push(...all.map(t=>[t.id,t.label]));const base=chartConfig;const bad=s=>{throw Error(s);};function n(v,k,min=0,max=1e8){if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>max)bad(k+' 使用 '+min+'–'+max+' 的有限數字。');}function pos(v,k){n(v,k,1e-6);}function text(v){if(typeof v!=='string'||!v.trim()||v.length>120)bad('名稱使用 1–120 字。');}function arr(v,k,max=30){if(!Array.isArray(v)||!v.length||v.length>max)bad(k+' 使用 1–'+max+' 個項目。');return v;}function day(v){if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v))bad('日期使用 YYYY-MM-DD。');const t=Date.parse(v+'T00:00:00Z');if(!Number.isFinite(t)||new Date(t).toISOString().slice(0,10)!==v)bad('日期不存在。');return t;}
function calc(d){let rows=[],labels=[],values=[],formula='',unit='分鐘',extra={};
if(d.type==='time_budget'){pos(d.available_minutes,'available_minutes');n(d.reserve_minutes,'reserve_minutes');arr(d.tasks,'tasks').forEach(s=>{text(s.title);n(s.minutes,'minutes');labels.push(s.title);values.push(s.minutes);});const total=values.reduce((a,b)=>a+b,0)+d.reserve_minutes;rows=d.tasks.map(s=>[s.title,s.minutes+' 分']);rows.push(['保留時間',d.reserve_minutes+' 分'],['总需求',total+' 分'],['剩餘／超額',d.available_minutes-total+' 分']);formula='需求 = Σ任務分鐘 + 保留分鐘；餘額 = 可用分鐘 − 需求；負值代表超額。';}
else if(d.type==='priority_value_effort'){const tasks=arr(d.tasks,'tasks').map(s=>{text(s.title);n(s.value_score,'value_score',0,10);pos(s.minutes,'minutes');return {...s,score:s.value_score/s.minutes};}).sort((a,b)=>b.score-a.score);rows=tasks.map(s=>[s.title,s.value_score+' 分 / '+s.minutes+' 分鐘',s.score.toFixed(4)]);labels=tasks.map(s=>s.title);values=tasks.map(s=>s.score);formula='排序值 = 主觀價值分數 / 所需分鐘；它是篩選線索，不能取代期限或必要性。';unit='價值分數/分鐘';}
else if(d.type==='pomodoro_planner'){pos(d.focus_minutes,'focus_minutes');for(const k of ['short_break','long_break'])n(d[k],k);n(d.rounds,'rounds',1,100);n(d.long_every,'long_every',1,100);if(!Number.isInteger(d.rounds)||!Number.isInteger(d.long_every))bad('rounds 和 long_every 必須為整數。');let total=0;for(let i=1;i<=d.rounds;i++){const rest=i===d.rounds?0:i%d.long_every===0?d.long_break:d.short_break;rows.push(['第 '+i+' 輪',d.focus_minutes+' 分專注',rest+' 分休息']);total+=d.focus_minutes+rest;}labels=['專注','休息'];values=[d.focus_minutes*d.rounds,total-d.focus_minutes*d.rounds];rows.push(['總歷時',total+' 分',(total/60).toFixed(2)+' 小時']);formula='最後一輪不加休息；每 long_every 輪以長休息取代短休息。本工具只估算時間，不是倒數計時器。';}
else if(d.type==='time_savings_roi'){n(d.setup_minutes,'setup_minutes');pos(d.saved_minutes_each,'saved_minutes_each');n(d.maintenance_minutes_each,'maintenance_minutes_each');n(d.uses,'uses',0,1e6);if(!Number.isInteger(d.uses))bad('uses 使用整數。');const net=d.saved_minutes_each-d.maintenance_minutes_each,benefit=net*d.uses-d.setup_minutes;labels=['每次淨節省','累計淨節省'];values=[net,benefit];rows=[['每次淨節省',net.toFixed(2)+' 分'],['回收次數',net>0?Math.ceil(d.setup_minutes/net)+' 次':d.setup_minutes===0&&net===0?'0 次（無淨節省）':'無法回收'],['累計淨節省',benefit.toFixed(2)+' 分']];formula='淨節省 = (每次節省 − 每次維護) × 次數 − 初始投入；正值才代表節省總時間。';}
else if(d.type==='meeting_person_hours'){pos(d.meeting_minutes,'meeting_minutes');arr(d.participants,'participants').forEach(s=>{text(s.title);n(s.minutes,'minutes');if(s.minutes>d.meeting_minutes)bad('參與者時間不可超過會議歷時。');labels.push(s.title);values.push(s.minutes);});const total=values.reduce((a,b)=>a+b,0);rows=d.participants.map(s=>[s.title,s.minutes+' 分']);rows.push(['會議歷時',d.meeting_minutes+' 分'],['團隊總投入',total+' 人分',(total/60).toFixed(2)+' 人時']);formula='團隊人時 = Σ每位實際參與分鐘 / 60；人時不同於會議歷時。';}
else if(d.type==='deadline_backplan'){let ms=day(d.deadline);pos(d.daily_minutes,'daily_minutes');if(d.daily_minutes>1440)bad('daily_minutes 不超過 1440。');arr(d.workdays,'workdays',7);if(d.workdays.some(v=>!Number.isInteger(v)||v<0||v>6)||new Set(d.workdays).size!==d.workdays.length)bad('工作日為不重複的 0（週一）到 6（週日）。');if(!Array.isArray(d.excluded_dates)||d.excluded_dates.length>100)bad('休假日期最多 100 個。');d.excluded_dates.forEach(day);arr(d.tasks,'tasks').forEach(s=>{text(s.title);pos(s.minutes,'minutes');});if(d.tasks.reduce((a,s)=>a+s.minutes,0)/d.daily_minutes>200)bad('最多排 200 個工作日。');const excluded=new Set(d.excluded_dates),pieces=[];let used=0,guard=0;for(const s of [...d.tasks].reverse()){let left=s.minutes;while(left>1e-7){if(++guard>3000)bad('排程範圍過大。');const date=new Date(ms).toISOString().slice(0,10),ok=d.workdays.includes((new Date(ms).getUTCDay()+6)%7)&&!excluded.has(date);if(!ok||used>=d.daily_minutes-1e-7){ms-=86400000;used=0;continue;}const take=Math.min(left,d.daily_minutes-used);pieces.push({date,title:s.title,minutes:take});used+=take;left-=take;}}pieces.reverse();rows=pieces.map(s=>[s.date,s.title,s.minutes.toFixed(2)+' 分']);labels=[...new Set(pieces.map(s=>s.date))];values=labels.map(v=>pieces.filter(s=>s.date===v).reduce((a,s)=>a+s.minutes,0));rows.push(['最遲開始日',labels[0],'截止 '+d.deadline]);formula='假設截止日整天可用，任務依序執行、按工作日逆向分配；不含提交時刻、緩衝或自動假日。';extra.pieces=pieces;}
else if(d.type==='critical_path_plan'){text(d.unit);arr(d.tasks,'tasks',30);const map=new Map();d.tasks.forEach(s=>{text(s.id);text(s.title);pos(s.duration,'duration');if(map.has(s.id)||!Array.isArray(s.depends)||s.depends.length>30||new Set(s.depends).size!==s.depends.length)bad('id 需唯一；depends 使用不重複前置 id。');map.set(s.id,{...s,es:0,ef:0});});const visiting=new Set(),done=new Set(),order=[];function visit(s){if(visiting.has(s.id))bad('前置任務不可循環。');if(done.has(s.id))return;visiting.add(s.id);for(const id of s.depends){if(!map.has(id))bad('前置任務不存在。');visit(map.get(id));s.es=Math.max(s.es,map.get(id).ef);}s.ef=s.es+s.duration;visiting.delete(s.id);done.add(s.id);order.push(s);}map.forEach(visit);const finish=Math.max(...order.map(s=>s.ef));[...order].reverse().forEach(s=>{const next=order.filter(v=>v.depends.includes(s.id));s.lf=next.length?Math.min(...next.map(v=>v.ls)):finish;s.ls=s.lf-s.duration;s.slack=s.ls-s.es;s.critical=Math.abs(s.slack)<1e-8;});rows=order.map(s=>[s.title,'ES '+s.es+' / EF '+s.ef,'LS '+s.ls+' / LF '+s.lf,'浮時 '+s.slack.toFixed(3)+(s.critical?'｜關鍵':'')]);rows.push(['最短專案歷時',finish+' '+d.unit,'關鍵工作：'+order.filter(s=>s.critical).map(s=>s.title).join('、')]);labels=order.map(s=>s.title);values=order.map(s=>s.duration);formula='ES=max(前置 EF)，EF=ES+工期；逆推 LS/LF，浮時=LS−ES。假設可平行、無資源競爭與休假。';unit=d.unit;extra.order=order;extra.finish=finish;}
else if(d.type==='time_variance_audit'){arr(d.tasks,'tasks').forEach(s=>{text(s.title);pos(s.planned_minutes,'planned_minutes');n(s.actual_minutes,'actual_minutes');labels.push(s.title);values.push(s.actual_minutes-s.planned_minutes);rows.push([s.title,s.planned_minutes+' / '+s.actual_minutes+' 分',((s.actual_minutes/s.planned_minutes-1)*100).toFixed(1)+'%']);});formula='差異 = 實際 − 計畫；差異% = (實際/計畫 − 1)×100%；正值為超時，負值為少用時間。';unit='差異分鐘';}
else if(d.type==='little_law_time'){n(d.average_wip,'average_wip');pos(d.throughput_per_hour,'throughput_per_hour');text(d.unit);const t=d.average_wip/d.throughput_per_hour;labels=['平均流程時間'];values=[t];rows=[['平均在製量',d.average_wip+' '+d.unit],['平均產出率',d.throughput_per_hour+' '+d.unit+'/小時'],['平均流程時間',t.toFixed(3)+' 小時',(t*60).toFixed(2)+' 分']];formula='L=λW，所以 W=L/λ；需相同流程邊界、觀察期間與長期穩定平均，不是單件交期保證。';unit='小時';}
return {rows,labels,values,formula,unit,...extra};}
chartConfig=function(d){if(!all.some(t=>t.id===d?.type))return base(d);text(d.title);if(d.type==='priority_eisenhower')return base({...d,type:'quadrant',x_label:'緊急程度（0–100）',y_label:'重要程度（0–100）',quadrants:['重要且不急｜排程','重要且緊急｜先做','不重要且不急｜刪減','不重要但緊急｜委派']});const r=calc(d),E=s=>safeText(String(s)),wrap=s=>{const a=Array.from(String(s)),out=[];while(a.length)out.push(E(a.splice(0,44).join('')));return out.join('<br>');};const cols=Math.max(...r.rows.map(s=>s.length)),heads=['項目／日期','結果／計算','說明','浮時與關鍵性'].slice(0,cols);const traces=[{type:'bar',x:r.labels.map(E),y:r.values,hovertemplate:'%{x}<br>%{y:.3f} '+E(r.unit)+'<extra></extra>'},{type:'table',domain:{y:[0,.52]},columnwidth:cols===4?[2,2,2,2]:undefined,header:{values:heads,height:36,align:'left',font:{size:13}},cells:{values:heads.map((_,i)=>r.rows.map(s=>wrap(s[i]||''))),height:46,align:'left',font:{size:12}}}];const layout={title:{text:E(d.title)+'<br><sup>'+E(r.rows.at(-1).join('｜')).slice(0,150)+'</sup>'},xaxis:{anchor:'y',automargin:true},yaxis:{domain:[.73,1],title:{text:E(r.unit)},automargin:true},annotations:[{xref:'paper',yref:'paper',x:0,y:.63,xanchor:'left',align:'left',text:wrap(r.formula),showarrow:false,font:{size:12}}],showlegend:false,margin:{t:110,l:75,r:35,b:40}};if(r.order){traces[0]={type:'bar',orientation:'h',x:r.order.map(s=>s.duration),base:r.order.map(s=>s.es),y:r.order.map(s=>E(s.title)+(s.critical?' ★':'')),customdata:r.order.map(s=>s.slack),hovertemplate:'%{y}<br>工期 %{x}<br>浮時 %{customdata}<extra></extra>'};layout.xaxis.title={text:E(d.unit)+'｜★ 為零浮時工作'};layout.yaxis.title={text:''};layout.yaxis.autorange='reversed';}return {traces,layout};};window.VCBusinessTime={calculate:calc,types:all.map(t=>t.id)};})();
