'use strict';
const FIELD_NAMES={title:'圖形標題',branches:'心智圖分支（可展開編輯）',x:'X 軸資料',y:'Y 軸資料',z:'Z 軸／高度資料',x_title:'X 軸名稱',y_title:'Y 軸名稱',series:'多組數據',labels:'分類／節點名稱',values:'數值／原始觀測值',size:'氣泡大小',measure:'瀑布圖數值類型',theta:'角度／雷達指標',r:'半徑／指標數值',ids:'節點唯一識別',parents:'父節點識別',source:'流量來源索引（從 0 開始）',target:'流量目標索引（從 0 開始）',dimensions:'平行座標維度',open:'開盤',high:'最高',low:'最低',close:'收盤',headers:'資料表欄名',rows:'資料表內容',width:'3D 長條寬度'};
let formMode=false,formModel=null,formFields=[];
function fieldHint(key,value){if(key==='branches')return '點＋子節點新增分支；留空的標題會在產生時提示錯誤。';if(key==='z'&&Array.isArray(value?.[0]))return '二維矩陣：每列對應 y、每欄對應 x。';if(Array.isArray(value)&&value.every(v=>typeof v==='number'))return '每行一個數字，或以逗號分隔；不可填單位。';if(Array.isArray(value)&&value.every(v=>typeof v==='string'))return '每行一個項目；不同陣列的筆數需一致。';return typeof value==='string'?'直接輸入文字。':'保留範例的 JSON 結構，修改其中數值或文字。';}
function readField(raw,mode){if(mode==='text')return raw;if(mode==='number'){const n=Number(raw);if(!raw.trim()||!Number.isFinite(n))throw Error('請輸入有效數字。');return n;}if(mode==='numbers'){const a=raw.split(/[\n,，]+/).map(s=>s.trim()).filter(Boolean);if(!a.length)throw Error('數字欄位不可留空。');return a.map(s=>{const n=Number(s);if(!Number.isFinite(n))throw Error('不是有效數字：'+s);return n;});}if(mode==='strings')return raw.split('\n').map(s=>s.trim()).filter(Boolean);return JSON.parse(raw);}
function branchEditor(nodes,host,depth=0){host.replaceChildren();nodes.forEach((node,index)=>{const row=document.createElement('div');row.className='branch-editor';const head=document.createElement('div');head.className='branch-head';const input=document.createElement('input');input.value=node.title;input.placeholder='節點名稱';input.setAttribute('aria-label','節點名稱');input.oninput=()=>node.title=input.value;const plus=document.createElement('button');plus.textContent='＋子節點';plus.type='button';const remove=document.createElement('button');remove.textContent='刪除';remove.type='button';plus.onclick=()=>{if(depth>=13){$('status').textContent='最多 15 層。';return;}(node.children??=[]).push({title:'新節點',children:[]});branchEditor(nodes,host,depth);};remove.onclick=()=>{nodes.splice(index,1);branchEditor(nodes,host,depth);};head.append(input,plus,remove);row.append(head);if(node.description){const note=document.createElement('input');note.value=node.description;note.setAttribute('aria-label','節點說明');note.oninput=()=>node.description=note.value;row.append(note);}const children=document.createElement('div');if(node.children?.length)branchEditor(node.children,children,depth+1);row.append(children);host.append(row);});}
function fillForm(data){formModel=structuredClone(data);formFields=[];const host=$('fields');host.replaceChildren();for(const [key,value]of Object.entries(formModel)){if(key==='type'||key==='schema_version'||key==='presentation')continue;const wrapper=document.createElement('label');wrapper.className='field';const name=document.createElement('strong');name.textContent=FIELD_NAMES[key]||key;wrapper.append(name);if(key==='branches'){const list=document.createElement('div');branchEditor(formModel.branches,list);const add=document.createElement('button');add.type='button';add.textContent='＋主要分支';add.onclick=()=>{formModel.branches.push({title:'新分支',children:[]});branchEditor(formModel.branches,list);};wrapper.append(list,add);}else{let mode=typeof value==='string'?'text':typeof value==='number'?'number':Array.isArray(value)&&value.every(v=>typeof v==='number')?'numbers':Array.isArray(value)&&value.every(v=>typeof v==='string')?'strings':'json';const input=document.createElement(mode==='text'||mode==='number'?'input':'textarea');input.setAttribute('aria-label',name.textContent);input.className='field-input';input.value=mode==='json'?JSON.stringify(value,null,2):['strings','numbers'].includes(mode)?value.join('\n'):String(value);if(mode==='number')input.type='number';wrapper.append(input);formFields.push({key,input,mode});}const hint=document.createElement('small');hint.textContent=fieldHint(key,value);wrapper.append(hint);host.append(wrapper);}}
function collectForm(){if(!formModel)throw Error('請先選擇架構。');const data=structuredClone(formModel);for(const f of formFields){try{data[f.key]=readField(f.input.value,f.mode);}catch(e){throw Error((FIELD_NAMES[f.key]||f.key)+'：'+e.message);}}return data;}
function showMode(form){formMode=form;$('formPanel').hidden=!form;$('input').hidden=form;$('fillMode').classList.toggle('primary',form);$('codeMode').classList.toggle('primary',!form);}
function applyTemplate(type){const data=chartExample(type);$('chartType').value=type;$('input').value=JSON.stringify(data,null,2);fillForm(data);showMode(true);$('library').close();$('status').textContent='已載入 '+CHARTS.find(c=>c[0]===type)[1]+' 架構。修改欄位後按「產生圖形」。';}
const originalGenerate=generate;
$('generate').onclick=()=>{try{if(formMode)$('input').value=JSON.stringify(collectForm(),null,2);originalGenerate();}catch(e){$('status').textContent='無法產生：'+e.message;}};
$('sample').onclick=()=>applyTemplate($('chartType').value);
$('fillMode').onclick=()=>{try{const d=JSON.parse($('input').value);if(d.schema_version==='1.0'){const n=normalize(d);const newer={type:'mindmap',title:n.title,branches:n.children.map(output)};fillForm(newer);}else fillForm(d);showMode(true);}catch(e){$('status').textContent='請先套用架構或貼入有效指令。';}};
$('codeMode').onclick=()=>{try{if(formMode)$('input').value=JSON.stringify(collectForm(),null,2);showMode(false);}catch(e){$('status').textContent=e.message;}};
$('templates').onclick=()=>$('library').showModal();$('closeLibrary').onclick=()=>$('library').close();
for(const [type,name]of CHARTS){const card=document.createElement('button');card.className='template-card';card.type='button';const title=document.createElement('strong');title.textContent=name;const subtitle=document.createElement('small');subtitle.textContent=type+' · 點選套用架構';card.append(title,subtitle);card.onclick=()=>applyTemplate(type);$('templateGrid').append(card);}
async function clipboard(text){try{await navigator.clipboard.writeText(text);$('status').textContent='已複製。';}catch{$('input').value=text;showMode(false);$('input').focus();$('input').select();$('status').textContent='瀏覽器未允許自動複製；文字已選取，請按 Ctrl+C／⌘C。';}}
$('copyCommand').onclick=()=>{try{const d=formMode?collectForm():JSON.parse($('input').value);clipboard(JSON.stringify(d,null,2));}catch(e){$('status').textContent=e.message;}};
$('copyPrompt').onclick=()=>{const type=$('chartType').value;clipboard('請將我提供的資料整理成 '+CHARTS.find(c=>c[0]===type)[1]+' 指令。只輸出合法 JSON，不加程式碼圍欄。依下面格式保留欄位與資料形狀，替換範例內容；陣列長度須一致。忠於來源，不能捏造數據。缺少必要資料時，先詢問我。這是合成範例：\n'+JSON.stringify(chartExample(type),null,2)+'\n\n我的資料：');};
fillForm(chartExample('mindmap'));showMode(true);
$('json').onclick=()=>{try{const d=formMode?collectForm():JSON.parse($('input').value);d.presentation=VCStyle.state();save(JSON.stringify(d,null,2),'application/json','visual-command.json');}catch(e){$('status').textContent=e.message;}};
const originalSync=sync;sync=()=>{originalSync();fillForm(JSON.parse($('input').value));};
