'use strict';
const FIELD_NAMES={title:'圖形標題',branches:'心智圖分支（可展開編輯）',x:'X 軸資料',y:'Y 軸資料',z:'Z 軸／高度資料',x_title:'X 軸名稱',y_title:'Y 軸名稱',series:'多組數據',labels:'分類／節點名稱',values:'數值／原始觀測值',size:'氣泡大小',measure:'瀑布圖數值類型',theta:'角度／雷達指標',r:'半徑／指標數值',ids:'節點唯一識別',parents:'父節點識別',source:'流量來源索引（從 0 開始）',target:'流量目標索引（從 0 開始）',dimensions:'平行座標維度',open:'開盤',high:'最高',low:'最低',close:'收盤',headers:'資料表欄名',rows:'資料表內容',width:'3D 長條寬度'};
Object.assign(FIELD_NAMES,{nodes:'概念節點（JSON）',relations:'關係連線（JSON）',root:'根節點與子節點（JSON）',steps:'步驟（JSON）',columns:'比较欄位／KWL 欄位',formulas:'公式與說明（JSON）',sections:'學習重點區塊（JSON）',effect:'要分析的問題',categories:'原因分類（JSON）',sets:'兩個集合（JSON）',intersection:'共同特徵',quadrants:'四個象限名稱',points:'學習項目位置（JSON）',events:'事件與日期（JSON）',levels:'金字塔層級（JSON）',cues:'提示／自問',notes:'內容筆記',summary:'自己的摘要',cards:'問題與答案（JSON）',topics:'主題與複習天數（JSON）',tasks:'任務開始與持續時間（JSON）',unit:'時間單位',note:'圖說'});
Object.assign(FIELD_NAMES,{lanes:'泳道角色',links:'流程交接（JSON）',participants:'參與者',messages:'訊息順序（JSON）',stages:'並行階段（JSON）',repeat_from:'返回連線起點（從 0 開始）',repeat_to:'返回的步驟（從 0 開始）',repeat_label:'返回條件',inputs:'輸入資料',process:'處理程序',outputs:'輸出成果',entities:'來源角色（JSON）',processes:'處理程序（JSON）',stores:'資料儲存（JSON）',flows:'資料流向（JSON）',month:'月份 YYYY-MM',entries:'每日紀錄（JSON）',blocks:'時間區塊（JSON）',milestones:'里程碑（JSON）',sessions:'學習／複習紀錄（JSON）',exam_date:'考試日期 YYYY-MM-DD',minutes:'各項分鐘數'});
let formMode=false,formModel=null,formFields=[];
function fieldHint(key,value){if(key==='parents')return '每行對應一個節點；根節點那一行請留空，空白行會保留。';if(key==='branches')return '點＋子節點新增分支；留空的標題會在產生時提示錯誤。';if(key==='z'&&Array.isArray(value?.[0]))return '二維矩陣：每列對應 y、每欄對應 x。';if(Array.isArray(value)&&value.every(v=>typeof v==='number'))return '每行一個數字，或以逗號分隔；不可填單位。';if(Array.isArray(value)&&value.every(v=>typeof v==='string'))return '每行一個項目；不同陣列的筆數需一致。';return typeof value==='string'?'直接輸入文字。':'保留範例的 JSON 結構，修改其中數值或文字。';}
function readField(raw,mode){if(mode==='text')return raw;if(mode==='number'){const n=Number(raw);if(!raw.trim()||!Number.isFinite(n))throw Error('請輸入有效數字。');return n;}if(mode==='numbers'){const a=raw.split(/[\n,，]+/).map(s=>s.trim()).filter(Boolean);if(!a.length)throw Error('數字欄位不可留空。');return a.map(s=>{const n=Number(s);if(!Number.isFinite(n))throw Error('不是有效數字：'+s);return n;});}if(mode==='parents')return raw.replace(/\r\n?/g,'\n').split('\n').map(s=>s.trim());if(mode==='strings')return raw.split('\n').map(s=>s.trim()).filter(Boolean);return JSON.parse(raw);}
function branchEditor(nodes,host,depth=0){host.replaceChildren();nodes.forEach((node,index)=>{const row=document.createElement('div');row.className='branch-editor';const head=document.createElement('div');head.className='branch-head';const input=document.createElement('input');input.value=node.title;input.placeholder='節點名稱';input.setAttribute('aria-label','節點名稱');input.oninput=()=>node.title=input.value;const plus=document.createElement('button');plus.textContent='＋子節點';plus.type='button';const remove=document.createElement('button');remove.textContent='刪除';remove.type='button';plus.onclick=()=>{if(depth>=13){$('status').textContent='最多 15 層。';return;}(node.children??=[]).push({title:'新節點',children:[]});branchEditor(nodes,host,depth);};remove.onclick=()=>{nodes.splice(index,1);branchEditor(nodes,host,depth);};head.append(input,plus,remove);row.append(head);if(node.description){const note=document.createElement('input');note.value=node.description;note.setAttribute('aria-label','節點說明');note.oninput=()=>node.description=note.value;row.append(note);}const children=document.createElement('div');if(node.children?.length)branchEditor(node.children,children,depth+1);row.append(children);host.append(row);});}
function fillForm(data){formModel=structuredClone(data);formFields=[];const host=$('fields');host.replaceChildren();for(const [key,value]of Object.entries(formModel)){if(key==='type'||key==='schema_version'||key==='presentation')continue;const wrapper=document.createElement('label');wrapper.className='field';const name=document.createElement('strong');name.textContent=FIELD_NAMES[key]||key;wrapper.append(name);if(key==='branches'){const list=document.createElement('div');branchEditor(formModel.branches,list);const add=document.createElement('button');add.type='button';add.textContent='＋主要分支';add.onclick=()=>{formModel.branches.push({title:'新分支',children:[]});branchEditor(formModel.branches,list);};wrapper.append(list,add);}else{let mode=key==='parents'?'parents':typeof value==='string'?'text':typeof value==='number'?'number':Array.isArray(value)&&value.length>0&&value.every(v=>typeof v==='number')?'numbers':Array.isArray(value)&&value.length>0&&value.every(v=>typeof v==='string')?'strings':'json';const input=document.createElement(mode==='text'||mode==='number'?'input':'textarea');input.setAttribute('aria-label',name.textContent);input.className='field-input';input.value=mode==='json'?JSON.stringify(value,null,2):['strings','numbers','parents'].includes(mode)?value.join('\n'):String(value);if(mode==='number')input.type='number';wrapper.append(input);formFields.push({key,input,mode});}const hint=document.createElement('small');hint.textContent=fieldHint(key,value);wrapper.append(hint);host.append(wrapper);}}
function collectForm(){if(!formModel)throw Error('請先選擇架構。');const data=structuredClone(formModel);for(const f of formFields){try{data[f.key]=readField(f.input.value,f.mode);}catch(e){throw Error((FIELD_NAMES[f.key]||f.key)+'：'+e.message);}}return data;}
function showMode(form){formMode=form;$('formPanel').hidden=!form;$('input').hidden=form;$('fillMode').classList.toggle('primary',form);$('codeMode').classList.toggle('primary',!form);}
function applyTemplate(type){const data=chartExample(type);$('chartType').value=type;$('input').value=JSON.stringify(data,null,2);fillForm(data);showMode(true);$('library').close();$('status').textContent='已載入 '+CHARTS.find(c=>c[0]===type)[1]+' 架構。修改欄位後按「產生圖形」。';}
const originalGenerate=generate;
$('generate').onclick=()=>{try{if(formMode)$('input').value=JSON.stringify(collectForm(),null,2);originalGenerate();}catch(e){$('status').textContent='無法產生：'+e.message;}};
$('sample').onclick=()=>applyTemplate($('chartType').value);
$('fillMode').onclick=()=>{try{const d=JSON.parse($('input').value);if(d.schema_version==='1.0'){const n=normalize(d);const newer={type:'mindmap',title:n.title,branches:n.children.map(output)};fillForm(newer);}else fillForm(d);showMode(true);}catch(e){$('status').textContent='請先套用架構或貼入有效指令。';}};
$('codeMode').onclick=()=>{try{if(formMode)$('input').value=JSON.stringify(collectForm(),null,2);showMode(false);}catch(e){$('status').textContent=e.message;}};
$('templates').onclick=()=>$('library').showModal();$('closeLibrary').onclick=()=>$('library').close();
for(const [type,name]of CHARTS){const card=document.createElement('button');card.className='template-card';card.type='button';const title=document.createElement('strong');title.textContent=name;const subtitle=document.createElement('small');const learning=window.VC_LEARNING_TEMPLATES?.find(t=>t.id===type);subtitle.textContent=learning?learning.desc+' · '+type:type+' · 點選套用架構';card.append(title,subtitle);card.onclick=()=>applyTemplate(type);$('templateGrid').append(card);}
async function clipboard(text){try{await navigator.clipboard.writeText(text);$('status').textContent='已複製。';}catch{$('input').value=text;showMode(false);$('input').focus();$('input').select();$('status').textContent='瀏覽器未允許自動複製；文字已選取，請按 Ctrl+C／⌘C。';}}
$('copyCommand').onclick=()=>{try{const d=formMode?collectForm():JSON.parse($('input').value);clipboard(JSON.stringify(d,null,2));}catch(e){$('status').textContent=e.message;}};
$('copyPrompt').onclick=()=>{const type=$('chartType').value;clipboard('請將我提供的資料整理成 '+CHARTS.find(c=>c[0]===type)[1]+' 指令。只輸出合法 JSON，不加程式碼圍欄。依下面格式保留欄位與資料形狀，替換範例內容；陣列長度須一致。忠於來源，不能捏造數據。缺少必要資料時，先詢問我。這是合成範例：\n'+JSON.stringify(chartExample(type),null,2)+'\n\n我的資料：');};
fillForm(chartExample('mindmap'));showMode(true);
$('json').onclick=()=>{try{const d=formMode?collectForm():JSON.parse($('input').value);if(chartData?.report)d.report=chartData.report;d.presentation=VCStyle.state();save(JSON.stringify(d,null,2),'application/json','visual-command.json');}catch(e){$('status').textContent=e.message;}};
const originalSync=sync;sync=()=>{originalSync();fillForm(JSON.parse($('input').value));};


Object.assign(FIELD_NAMES,{counts:"缺失次數",lsl:"規格下限 LSL",usl:"規格上限 USL",target:"目標值",within_sigma:"組內標準差 σ（0 表示未提供）",bins:"直方圖組數"});

Object.assign(FIELD_NAMES,{point:"P 觀點",reason:"R 理由",example:"E 例子／證據",restatement:"P 重申與行動",strengths:"S 優勢",weaknesses:"W 弱勢",opportunities:"O 機會",threats:"T 威脅",so:"SO 運用優勢掌握機會",st:"ST 運用優勢應對威脅",wo:"WO 改善弱勢掌握機會",wt:"WT 降低弱勢避開威脅",situation:"S 情境",complication:"C 衝突",question:"Q 問題",answer:"A 答案"});

Object.assign(FIELD_NAMES,{key_partners:"關鍵夥伴",key_activities:"關鍵活動",key_resources:"關鍵資源",value_propositions:"價值主張",customer_relationships:"顧客關係",channels:"通路",customer_segments:"顧客族群",cost_structure:"成本結構",revenue_streams:"收入來源",customer_jobs:"顧客任務",pains:"顧客痛點",gains:"期望收穫",products_services:"產品與服務",pain_relievers:"痛點解方",gain_creators:"收穫創造",political:"政治因素",economic:"經濟因素",social:"社會因素",technological:"科技因素",environmental:"環境因素",legal:"法律因素",rivalry:"既有競爭者",new_entrants:"新進入者威脅",substitutes:"替代品威脅",supplier_power:"供應商議價力",buyer_power:"買方議價力",attention:"A 注意",interest:"I 興趣",desire:"D 渴望",action:"A 行動",objective:"目標 Objective",key_results:"關鍵成果 Key Results",baseline:"起點值",current:"目前值",target:"目標值",direction:"方向（increase／decrease）"});

Object.assign(FIELD_NAMES,{periods:"比較期間（產出、人數、每人工時）",output_unit:"產出單位",planned_minutes:"計畫生產時間（分鐘）",stop_minutes:"停機時間（分鐘）",ideal_cycle_seconds:"理想週期（秒／件）",total_count:"總生產件數",good_count:"良品件數",station_seconds:"各工作站總負荷（秒）",cycle_seconds:"產線週期（秒）",planned_input:"計畫投入量",actual_input:"實際投入量",planned_output:"目標產出量",actual_output:"實際產出量",input_unit:"投入單位",net_minutes:"淨可用生產時間（分鐘）",demand:"同期間需求（件）",actual_cycle_seconds:"實際週期（秒／件）",setup_minutes:"準備時間（分鐘）",buffer_percent:"時間緩衝（%）",jobs:"加工需求（数量與每件分鐘）",available_minutes:"淨可用產能（分鐘）",start_date:"計畫開始日期 YYYY-MM-DD",daily_minutes:"每日可用分鐘",workdays:"工作日（0 週一～6 週日）",excluded_dates:"額外休假日期（每行 YYYY-MM-DD）"});

Object.assign(FIELD_NAMES,{reserve_minutes:"保留時間（分鐘）",focus_minutes:"每輪專注（分鐘）",rounds:"專注輪數",short_break:"短休息（分鐘）",long_break:"長休息（分鐘）",long_every:"每幾輪長休息",saved_minutes_each:"每次節省分鐘",maintenance_minutes_each:"每次維護分鐘",uses:"使用次數",participants:"參與者與分鐘",meeting_minutes:"會議歷時（分鐘）",deadline:"截止日期 YYYY-MM-DD",average_wip:"平均在製量",throughput_per_hour:"平均每小時產出",value_score:"價值分數（0–10）"});
