/* Command adapters for Plotly; no code evaluation or AI calls. */
'use strict';
const CHARTS=[['mindmap','心智圖'],['line','折線圖'],['bar','長條圖'],['grouped_bar','群組長條圖'],['stacked_bar','堆疊長條圖'],['area','面積圖'],['stacked_area','堆疊面積圖'],['scatter','散佈圖'],['bubble','氣泡圖'],['pie','圓餅圖'],['donut','環圈圖'],['histogram','直方圖'],['box','箱形圖'],['violin','小提琴圖'],['heatmap','熱力圖'],['contour','等高線圖'],['scatter3d','3D 散佈圖'],['line3d','3D 折線圖'],['surface','3D 曲面圖'],['bar3d','3D 長條圖'],['waterfall','瀑布圖'],['funnel','漏斗圖'],['radar','雷達圖'],['polar','極座標圖'],['treemap','矩形樹圖'],['sunburst','旭日圖'],['sankey','桑基圖'],['parallel','平行座標圖'],['candlestick','K 線圖'],['table','資料表']];
function numbers(a,name){if(!Array.isArray(a)||!a.length||a.some(v=>typeof v!=='number'||!Number.isFinite(v)))throw Error(name+' 需要非空數字陣列。');return a;}
function array(a,name){if(!Array.isArray(a)||!a.length||a.some(v=>!['number','string'].includes(typeof v)||(typeof v==='number'&&!Number.isFinite(v))))throw Error(name+' 需要非空文字或數字陣列。');return a;}
function equal(a,b,name){if(a.length!==b.length)throw Error(name+' 的長度必須一致。');}
function matrix(a){if(!Array.isArray(a)||!a.length)throw Error('z 需要二維數字陣列。');a.forEach(r=>numbers(r,'z'));if(a.some(r=>r.length!==a[0].length))throw Error('z 每列長度必須一致。');return a;}
function safeText(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function chartConfig(d){if(!d||!CHARTS.some(c=>c[0]===d.type)||d.type==='mindmap')throw Error('不支援的圖表 type。');if(typeof d.title!=='string'||!d.title.trim())throw Error('需要 title。');const t=d.type,traces=[],layout={title:{text:safeText(d.title)},margin:{t:75,l:70,r:40,b:70},paper_bgcolor:'#f7f8fc',plot_bgcolor:'#ffffff',font:{family:'system-ui,sans-serif',color:'#243046'},colorway:['#6965db','#25a390','#e2a746','#d46c93','#498fc9'],autosize:true};
function xy(s){array(s.x,'x');numbers(s.y,'y');equal(s.x,s.y,'x/y');return {x:s.x.map(v=>typeof v==='string'?safeText(v):v),y:s.y,name:safeText(s.name||'資料')};}
if(['line','bar','grouped_bar','stacked_bar','area','stacked_area','scatter','bubble'].includes(t)){
 const series=d.series||[d];if(!Array.isArray(series)||!series.length)throw Error('series 需要非空陣列。');if(['grouped_bar','stacked_bar','stacked_area'].includes(t)&&series.length<2)throw Error('此圖需要至少兩組 series。');series.forEach(s=>{const base=xy(s);if(['bar','grouped_bar','stacked_bar'].includes(t))traces.push({...base,type:'bar'});else{const trace={...base,type:'scatter',mode:['scatter','bubble'].includes(t)?'markers':'lines+markers'};if(t==='area')trace.fill='tozeroy';if(t==='stacked_area')trace.stackgroup='all';if(t==='bubble'){numbers(s.size,'size');equal(s.size,s.y,'size/y');if(s.size.some(v=>v<=0))throw Error('size 必須大於 0。');trace.marker={size:s.size,sizemode:'area',sizeref:2*Math.max(...s.size)/45**2,sizemin:4};}traces.push(trace);}});if(t==='grouped_bar')layout.barmode='group';if(t==='stacked_bar')layout.barmode='stack';
}else if(['pie','donut','funnel','waterfall'].includes(t)){
 array(d.labels,'labels');numbers(d.values,'values');equal(d.labels,d.values,'labels/values');const labels=d.labels.map(safeText);if(['pie','donut','funnel'].includes(t)&&d.values.some(v=>v<0))throw Error('此圖的 values 不可為負數。');if(['pie','donut'].includes(t)){if(!d.values.some(v=>v>0))throw Error('圓餅數值不可全部為零。');traces.push({type:'pie',labels,values:d.values,hole:t==='donut'?.55:0});}else if(t==='funnel')traces.push({type:'funnel',y:labels,x:d.values});else{if(!Array.isArray(d.measure)||d.measure.length!==d.values.length||d.measure.some(v=>!['relative','total','absolute'].includes(v)))throw Error('瀑布圖需要 measure 陣列（relative/total/absolute）。');traces.push({type:'waterfall',x:labels,y:d.values,measure:d.measure});}
}else if(['histogram','box','violin'].includes(t)){
 const groups=d.series||[d];if(!Array.isArray(groups)||!groups.length)throw Error('series 需為非空陣列。');groups.forEach(s=>{numbers(s.values,'values');traces.push(t==='histogram'?{type:t,x:s.values,name:safeText(s.name||'資料')}:{type:t,y:s.values,name:safeText(s.name||'資料'),box:t==='violin'?{visible:true}:undefined,points:t==='violin'?'all':undefined});});
}else if(['heatmap','contour','surface'].includes(t)){
 matrix(d.z);array(d.x,'x');array(d.y,'y');if(d.x.length!==d.z[0].length||d.y.length!==d.z.length)throw Error('z 欄數需等於 x 長度，列數需等於 y 長度。');if(t!=='heatmap'){numbers(d.x,'x');numbers(d.y,'y');}traces.push({type:t,x:d.x.map(v=>typeof v==='string'?safeText(v):v),y:d.y.map(v=>typeof v==='string'?safeText(v):v),z:d.z,colorscale:'Viridis'});
}else if(['scatter3d','line3d','bar3d'].includes(t)){
 numbers(d.x,'x');numbers(d.y,'y');numbers(d.z,'z');equal(d.x,d.y,'x/y');equal(d.x,d.z,'x/z');
 layout.margin={t:82,l:24,r:24,b:24};
 layout.scene={aspectmode:'cube',camera:{eye:{x:1.25,y:1.25,z:.9}},xaxis:{title:{text:safeText(d.x_title||'X'),font:{size:13}},tickfont:{size:11},showspikes:false},yaxis:{title:{text:safeText(d.y_title||'Y'),font:{size:13}},tickfont:{size:11},showspikes:false},zaxis:{title:{text:safeText(d.z_title||'Z'),font:{size:13}},tickfont:{size:11},showspikes:false}};
 if(t==='bar3d'){if(d.x.length>200)throw Error('3D 長條最多 200 根。');const dx=d.width??.6;if(typeof dx!=='number'||!Number.isFinite(dx)||dx<=0)throw Error('width 需為正數。');d.x.forEach((x,q)=>{const y=d.y[q],z=d.z[q],h=dx/2;traces.push({type:'mesh3d',x:[x-h,x+h,x+h,x-h,x-h,x+h,x+h,x-h],y:[y-h,y-h,y+h,y+h,y-h,y-h,y+h,y+h],z:[0,0,0,0,z,z,z,z],i:[0,0,4,4,0,0,1,1,2,2,3,3],j:[1,2,5,6,1,5,2,6,3,7,0,4],k:[2,3,6,7,5,4,6,5,7,6,4,7],color:['#6965db','#25a390','#e2a746'][q%3],opacity:.9,flatshading:true,name:safeText('長條 '+(q+1)),hovertemplate:'高度：'+z+'<extra></extra>'});});}else traces.push({type:'scatter3d',x:d.x,y:d.y,z:d.z,mode:t==='line3d'?'lines+markers':'markers',marker:{size:5,color:d.z,colorscale:'Viridis'},hovertemplate:'X：%{x}<br>Y：%{y}<br>Z：%{z}<extra></extra>'});
}else if(['radar','polar'].includes(t)){
 const ss=d.series||[d];if(!Array.isArray(ss)||!ss.length)throw Error('series 需要非空陣列。');ss.forEach(s=>{array(s.theta,'theta');numbers(s.r,'r');equal(s.theta,s.r,'theta/r');const theta=s.theta.map(v=>typeof v==='string'?safeText(v):v),r=[...s.r];if(t==='radar'){theta.push(theta[0]);r.push(r[0]);}traces.push({type:'scatterpolar',theta,r,fill:t==='radar'?'toself':'none',mode:'lines+markers',name:safeText(s.name||'資料')});});
}else if(['treemap','sunburst'].includes(t)){
 array(d.ids,'ids');array(d.labels,'labels');if(!Array.isArray(d.parents)||d.parents.length!==d.ids.length)throw Error('parents 需與 ids 長度一致。');numbers(d.values,'values');equal(d.ids,d.labels,'ids/labels');equal(d.ids,d.values,'ids/values');if(new Set(d.ids).size!==d.ids.length)throw Error('ids 不可重複。');if(d.values.some(v=>v<0))throw Error('values 不可為負數。');const ids=new Set(d.ids);if(d.parents.some(p=>p!==''&&!ids.has(p)))throw Error('parents 必須指向既有 id 或空字串。');for(let i=0;i<d.ids.length;i++){let j=i;const seen=new Set();while(d.parents[j]!==''){if(seen.has(j))throw Error('階層不可循環。');seen.add(j);j=d.ids.indexOf(d.parents[j]);}}traces.push({type:t,ids:d.ids.map(safeText),labels:d.labels.map(safeText),parents:d.parents.map(safeText),values:d.values,branchvalues:'remainder'});
}else if(t==='sankey'){
 array(d.labels,'labels');numbers(d.source,'source');numbers(d.target,'target');numbers(d.values,'values');equal(d.source,d.target,'source/target');equal(d.source,d.values,'source/values');if([...d.source,...d.target].some(i=>!Number.isInteger(i)||i<0||i>=d.labels.length)||d.values.some(v=>v<0))throw Error('來源／目標需為合法節點索引，values 不可為負數。');traces.push({type:t,node:{label:d.labels.map(safeText),pad:20,thickness:22},link:{source:d.source,target:d.target,value:d.values}});
}else if(t==='parallel'){
 if(!Array.isArray(d.dimensions)||d.dimensions.length<2)throw Error('dimensions 至少兩欄。');d.dimensions.forEach(s=>numbers(s.values,'維度 values'));if(d.dimensions.some(s=>s.values.length!==d.dimensions[0].values.length))throw Error('各維度筆數需一致。');
 layout.margin={t:88,l:48,r:48,b:42};
 traces.push({type:'parcoords',domain:{x:[.06,.94],y:[.08,.92]},labelfont:{size:13},tickfont:{size:10},rangefont:{size:10},dimensions:d.dimensions.map(s=>({label:safeText(s.label||'維度'),values:s.values}))});
}else if(t==='candlestick'){
 array(d.x,'x');for(const k of ['open','high','low','close']){numbers(d[k],k);equal(d.x,d[k],'x/'+k);}if(d.high.some((v,i)=>v<Math.max(d.open[i],d.close[i],d.low[i]))||d.low.some((v,i)=>v>Math.min(d.open[i],d.close[i],d.high[i])))throw Error('high/low 必須涵蓋 open/close。');traces.push({type:t,x:d.x.map(safeText),open:d.open,high:d.high,low:d.low,close:d.close});layout.xaxis={rangeslider:{visible:false}};
}else if(t==='table'){
 array(d.headers,'headers');if(!Array.isArray(d.rows)||!d.rows.length||d.rows.some(r=>!Array.isArray(r)||r.length!==d.headers.length||r.some(v=>!['string','number'].includes(typeof v))))throw Error('rows 需為與 headers 欄數一致的二維資料。');traces.push({type:'table',header:{values:d.headers.map(safeText),fill:{color:'#6965db'},font:{color:'white'},height:34},cells:{values:d.headers.map((_,i)=>d.rows.map(r=>safeText(r[i]))),height:30,fill:{color:'#edf0fc'}}});
}
if(!traces.length)throw Error('沒有可繪製的資料。');const is3d=['scatter3d','line3d','bar3d','surface'].includes(t);if(!is3d){if(d.x_title)layout.xaxis={...layout.xaxis,title:{text:safeText(d.x_title)}};if(d.y_title)layout.yaxis={...layout.yaxis,title:{text:safeText(d.y_title)}};}return {traces,layout};}
function chartExample(type){const base={type,title:CHARTS.find(c=>c[0]===type)?.[1]+'｜示範資料'};
const xy={x:['一月','二月','三月','四月'],y:[12,18,15,24]};
if(type==='mindmap')return {type,title:'我的學習系統',branches:[{title:'課前',children:[{title:'閱讀講義'},{title:'整理問題'}]},{title:'課後',children:[{title:'練習'},{title:'複習'}]}]};
if(['line','bar','area'].includes(type))return {...base,...xy,x_title:'月份',y_title:'數量'};
if(['grouped_bar','stacked_bar','stacked_area'].includes(type))return {...base,series:[{name:'甲組',...xy},{name:'乙組',x:xy.x,y:[8,13,11,19]}]};
if(['scatter','bubble'].includes(type))return {...base,x:[1,2,3,4,5],y:[3,5,4,8,10],...(type==='bubble'?{size:[10,25,15,40,30]}:{})};
if(['pie','donut','funnel'].includes(type))return {...base,labels:['甲','乙','丙','丁'],values:[40,30,20,10]};
if(['histogram','box','violin'].includes(type))return {...base,values:[12,13,14,14,15,15,15,16,17,18,18,20,25]};
if(['heatmap','contour','surface'].includes(type))return {...base,x:[0,1,2,3],y:[0,1,2,3],z:[[1,2,3,2],[2,4,6,3],[3,6,9,5],[2,3,5,3]]};
if(['scatter3d','line3d','bar3d'].includes(type))return {...base,x:[0,1,2,3],y:[0,1,0,1],z:[2,5,3,7]};
if(type==='waterfall')return {...base,labels:['期初','收入','支出','期末'],values:[100,60,-30,0],measure:['absolute','relative','relative','total']};
if(type==='radar')return {...base,theta:['理解','記憶','應用','表達','解題'],r:[7,8,6,9,7]};
if(type==='polar')return {...base,theta:[0,60,120,180,240,300],r:[3,5,4,6,4,5]};
if(['treemap','sunburst'].includes(type))return {...base,ids:['root','a','b','a1','a2'],labels:['主題','分支甲','分支乙','子甲','子乙'],parents:['','root','root','a','a'],values:[0,0,6,4,5]};
if(type==='sankey')return {...base,labels:['原料','加工','產品','損耗'],source:[0,1,1],target:[1,2,3],values:[10,8,2]};
if(type==='parallel')return {...base,dimensions:[{label:'成本',values:[10,15,12,18]},{label:'品質',values:[80,95,85,90]},{label:'速度',values:[5,3,4,2]}]};
if(type==='candlestick')return {...base,x:['2026-01-01','2026-01-02','2026-01-03'],open:[10,12,11],high:[14,15,14],low:[9,10,10],close:[12,11,13]};
if(type==='table')return {...base,headers:['品項','數量','成本'],rows:[['甲',12,100],['乙',18,150],['丙',15,120]]};throw Error('無範例');}
let plotlyPromise;
function localRuntime(){return location.protocol==='file:'||['localhost','127.0.0.1','::1'].includes(location.hostname);}
function loadScriptOnce(src,globalName){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.async=true;s.onload=()=>window[globalName]?resolve(window[globalName]):reject(Error(globalName+' 載入完成但全域物件不存在。'));s.onerror=()=>{s.remove();reject(Error('無法載入 '+src));};document.head.append(s);});}
async function loadPlotly(){if(window.Plotly)return window.Plotly;if(plotlyPromise)return plotlyPromise;plotlyPromise=(async()=>{try{return await loadScriptOnce('assets/vendor/plotly-4.1.1.min.js','Plotly');}catch(localError){try{return await loadScriptOnce('https://cdn.plot.ly/plotly-4.1.1.min.js','Plotly');}catch{throw Error('Plotly 載入失敗。若要完全離線使用，請先執行 setup-offline.command（Windows：setup-offline.bat）。');}}})();try{return await plotlyPromise;}catch(e){plotlyPromise=null;throw e;}}
