'use strict';
const PALETTES={research:['#0072B2','#D55E00','#009E73','#CC79A7','#E69F00','#56B4E9'],business:['#24476A','#397F8A','#C18437','#806293','#526477','#B24C49'],mono:['#222222','#666666','#999999','#444444','#BBBBBB']};
function finite(v,name){if(typeof v!=='number'||!Number.isFinite(v))throw Error(name+' 必須是有限數字。');}
function num(a,name){if(!Array.isArray(a)||!a.length||a.length>2000)throw Error(name+' 需為 1–2000 筆陣列。');a.forEach(v=>finite(v,name));}
function labels(a){if(!Array.isArray(a)||!a.length||a.some(v=>typeof v!=='string'||!v.trim()))throw Error('labels 需要非空文字陣列。');}
function same(...arrays){if(arrays.some(a=>a.length!==arrays[0].length))throw Error('對應陣列筆數需一致。');}
function validateResearch(doc){if(!doc||doc.version!=='1.0'||typeof doc.title!=='string'||!doc.title.trim())throw Error('需要 version:"1.0" 與 title。');const item=RESEARCH_CATALOG.find(x=>x.id===doc.type);if(!item||!doc.data)throw Error('type 或 data 不正確。');for(const k of ['title','subtitle','caption','source','x_label','y_label'])if(doc[k]!==undefined&&(typeof doc[k]!=='string'||doc[k].length>2000))throw Error(k+' 需為不超過 2000 字的文字。');const d=doc.data;
if(item.engine==='mermaid'){if(typeof d.code!=='string'||d.code.length>20000)throw Error('code 需為 20000 字內的 Mermaid 文字。');if(/%%\s*\{|^\s*---|\bclick\s|<\/?(?:script|iframe)\b/i.test(d.code))throw Error('不接受初始化指令、前置設定或點擊動作。');const prefixes={flowchart:/^\s*(flowchart|graph)\b/,sequence:/^\s*sequenceDiagram\b/,gantt:/^\s*gantt\b/,state:/^\s*stateDiagram-v2\b/,class:/^\s*classDiagram\b/,er:/^\s*erDiagram\b/};if(!prefixes[doc.type].test(d.code))throw Error('Mermaid 圖形語法與 type 不一致。');return item;}
if(['errorbar','forest'].includes(doc.type)){labels(d.labels);for(const k of ['estimate','lower','upper'])num(d[k],k);same(d.labels,d.estimate,d.lower,d.upper);if(d.estimate.some((v,i)=>v<d.lower[i]||v>d.upper[i]))throw Error('估計值必須介於 lower 與 upper 之間。');if(d.reference!==undefined)finite(d.reference,'reference');}
if(doc.type==='dumbbell'){labels(d.labels);num(d.before,'before');num(d.after,'after');same(d.labels,d.before,d.after);}
if(['pareto','control'].includes(doc.type)){labels(d.labels);num(d.values,'values');same(d.labels,d.values);if(doc.type==='pareto'&&(d.values.some(v=>v<0)||!d.values.some(v=>v>0)))throw Error('次數需非負且總和大於 0。');if(doc.type==='control'){['center','lcl','ucl'].forEach(k=>finite(d[k],k));if(d.lcl>d.center||d.ucl<d.center)throw Error('需要 lcl ≤ center ≤ ucl。');}}
if(doc.type==='network'){if(!Array.isArray(d.nodes)||!d.nodes.length||d.nodes.length>300||!Array.isArray(d.links))throw Error('nodes 需為 1–300 個節點，links 需為陣列。');const ids=new Set();d.nodes.forEach(n=>{if(typeof n.id!=='string'||!n.id||ids.has(n.id)||typeof n.name!=='string')throw Error('節點需有唯一 id 與 name。');ids.add(n.id);});if(d.links.some(l=>!ids.has(l.source)||!ids.has(l.target)))throw Error('連線需指向既有節點。');}
if(doc.type==='tree'){let count=0;function walk(n,level){if(!n||typeof n.name!=='string'||level>15||++count>500)throw Error('樹節點格式、深度或數量超限。');if(n.children!==undefined){if(!Array.isArray(n.children))throw Error('children 需為陣列。');n.children.forEach(c=>walk(c,level+1));}}walk(d.root,0);}
if(doc.type==='calendar'){if(typeof d.range!=='string'||!/^\d{4}(-\d{2})?$/.test(d.range)||!Array.isArray(d.values)||!d.values.length)throw Error('range 應為 YYYY 或 YYYY-MM，values 為日期數值陣列。');const dates=new Set();d.values.forEach(row=>{if(!Array.isArray(row)||row.length!==2||typeof row[0]!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(row[0])||!row[0].startsWith(d.range)||dates.has(row[0]))throw Error('日期需唯一、在 range 內並符合 YYYY-MM-DD。');const date=new Date(row[0]+'T00:00:00Z');if(!Number.isFinite(date.getTime())||date.toISOString().slice(0,10)!==row[0])throw Error('不存在的日期。');finite(row[1],'每日數值');dates.add(row[0]);});}return item;}
function researchOption(doc,theme='research'){validateResearch(doc);const d=doc.data,p=typeof VCStyle==='undefined'?(PALETTES[theme]||PALETTES.research):theme==='mono'?(VCStyle.state().background==='black'?['#ffffff','#bbbbbb','#888888']:PALETTES.mono):VCStyle.palette();const axis={type:'value',nameTextStyle:{fontSize:13,color:'#374151'},axisLabel:{fontSize:12,color:'#475569'},axisLine:{lineStyle:{color:'#64748b'}},splitLine:{lineStyle:{color:'#e5e7eb'}},nameLocation:'middle',nameGap:40};const o={animation:false,backgroundColor:'#fff',color:p,textStyle:{fontFamily:'Arial, "Noto Sans TC", sans-serif',fontSize:13},grid:{left:95,right:70,top:60,bottom:85,containLabel:true},tooltip:{trigger:'axis',renderMode:'richText'},legend:{top:5},xAxis:{...axis,name:doc.x_label||''},yAxis:{...axis,name:doc.y_label||''},series:[]};const category={...axis,name:doc.x_label||'',type:'category',data:d.labels,axisTick:{alignWithLabel:true},splitLine:{show:false}};
if(doc.type==='pareto'){const rows=d.labels.map((label,i)=>({label,value:d.values[i]})).sort((a,b)=>b.value-a.value),total=rows.reduce((s,x)=>s+x.value,0);let sum=0;o.xAxis={...category,data:rows.map(r=>r.label)};o.yAxis=[{...axis,name:doc.y_label||'次數'},{...axis,name:'累積百分比 (%)',min:0,max:100,position:'right'}];o.series=[{type:'bar',name:'次數',data:rows.map(r=>r.value),barMaxWidth:45},{type:'line',name:'累積百分比',yAxisIndex:1,data:rows.map(r=>100*(sum+=r.value)/total),symbol:'diamond',lineStyle:{type:'dashed',width:2}}];}
if(doc.type==='control'){o.xAxis=category;o.series=[{type:'line',name:'量測值',data:d.values.map(v=>({value:v,symbolSize:v<d.lcl||v>d.ucl?12:7,itemStyle:{color:v<d.lcl||v>d.ucl?p[1]:p[0]}})),symbol:'circle',lineStyle:{width:2}},{type:'line',name:'CL',data:d.values.map(()=>d.center),symbol:'none',lineStyle:{color:'#64748b',type:'solid'}},{type:'line',name:'UCL',data:d.values.map(()=>d.ucl),symbol:'none',lineStyle:{color:p[1],type:'dashed'}},{type:'line',name:'LCL',data:d.values.map(()=>d.lcl),symbol:'none',lineStyle:{color:p[1],type:'dashed'}}];}
if(['forest','errorbar','dumbbell'].includes(doc.type)){const horizontal=doc.type!=='errorbar';if(horizontal){o.yAxis={...category,name:doc.y_label||'',inverse:true};o.xAxis={...axis,name:doc.x_label||'估計值',scale:true};}else{o.xAxis=category;o.yAxis={...axis,name:doc.y_label||'估計值',scale:true};}const rows=d.labels.map((_,i)=>[i,doc.type==='dumbbell'?d.before[i]:d.lower[i],doc.type==='dumbbell'?d.after[i]:d.upper[i]]);o.series=[{name:doc.type==='dumbbell'?'前後連線':'提供的區間',type:'custom',data:rows,encode:horizontal?{x:[1,2],y:0}:{x:0,y:[1,2]},renderItem:(params,api)=>{const i=api.value(0),a=api.coord(horizontal?[api.value(1),i]:[i,api.value(1)]),b=api.coord(horizontal?[api.value(2),i]:[i,api.value(2)]);const line=(x1,y1,x2,y2)=>({type:'line',shape:{x1,y1,x2,y2},style:{stroke:p[0],lineWidth:2}});return {type:'group',children:[line(a[0],a[1],b[0],b[1]),...(doc.type==='dumbbell'?[]:horizontal?[line(a[0],a[1]-5,a[0],a[1]+5),line(b[0],b[1]-5,b[0],b[1]+5)]:[line(a[0]-5,a[1],a[0]+5,a[1]),line(b[0]-5,b[1],b[0]+5,b[1])])]};}}];for(const [name,values,symbol,color]of doc.type==='dumbbell'?[['之前',d.before,'circle',p[0]],['之後',d.after,'diamond',p[1]]]:[['估計值',d.estimate,'circle',p[0]]])o.series.push({type:'scatter',name,data:values.map((v,i)=>horizontal?[v,i]:[i,v]),symbol,symbolSize:10,itemStyle:{color}});if(doc.type==='forest'&&d.reference!==undefined)o.series[1].markLine={silent:true,symbol:'none',data:[{xAxis:d.reference}],lineStyle:{type:'dashed',color:'#888'},label:{show:false}};o.tooltip={trigger:'item',renderMode:'richText'};}
if(doc.type==='network'){delete o.xAxis;delete o.yAxis;o.tooltip={trigger:'item',renderMode:'richText'};o.series=[{type:'graph',layout:'force',data:d.nodes.map((n,i)=>({...n,symbolSize:40,itemStyle:{color:p[i%p.length]}})),links:d.links.map(l=>({source:l.source,target:l.target})),roam:true,draggable:true,label:{show:true,position:'right'},edgeSymbol:['none','arrow'],lineStyle:{color:'#8b98a9',curveness:.12},force:{repulsion:400,edgeLength:130}}];}
if(doc.type==='tree'){delete o.xAxis;delete o.yAxis;o.series=[{type:'tree',data:[d.root],top:30,bottom:30,left:65,right:160,symbolSize:9,initialTreeDepth:-1,label:{position:'left',align:'right',fontSize:13},leaves:{label:{position:'right',align:'left'}},lineStyle:{color:'#9aaabc'},expandAndCollapse:true,roam:true}];}
if(doc.type==='calendar'){delete o.xAxis;delete o.yAxis;const vals=d.values.map(r=>r[1]);o.visualMap={min:Math.min(...vals),max:Math.max(...vals)||1,calculable:true,orient:'horizontal',left:'center',bottom:25,inRange:{color:theme==='mono'?['#eee','#222']:['#eef6fa','#91bfd1','#0072b2']}};o.calendar={range:d.range,top:80,left:80,right:60,cellSize:['auto',35],yearLabel:{show:false},dayLabel:{firstDay:1,nameMap:['日','一','二','三','四','五','六']},monthLabel:{nameMap:'en'},itemStyle:{borderColor:'#fff',borderWidth:3}};o.series=[{type:'heatmap',coordinateSystem:'calendar',data:d.values}];o.tooltip={position:'top',renderMode:'richText'};}return o;}
