/* Independent thinking and note templates. These are generic structures, not reproductions of books. */
'use strict';
RESEARCH_CATALOG.push(
{id:'concept',name:'概念圖',group:'視覺化思考',engine:'echarts',purpose:'節點、箭頭與關係連接詞組成命題；關係不一定是因果。',data:{nodes:[{id:'a',name:'主動提取'},{id:'b',name:'測驗練習'},{id:'c',name:'回饋'},{id:'d',name:'知識修正'}],links:[{source:'b',target:'a',relation:'是一種'},{source:'b',target:'c',relation:'可搭配'},{source:'c',target:'d',relation:'協助'}]}},
{id:'causal',name:'因果循環圖',group:'視覺化思考',engine:'echarts',purpose:'連線標示同向（+）或反向（−）影響；符號不是好壞，圖形本身不證明因果。',data:{nodes:[{id:'a',name:'練習量'},{id:'b',name:'熟練度'},{id:'c',name:'練習意願'}],links:[{source:'a',target:'b',relation:'+',note:'假設：其他條件不變'},{source:'b',target:'c',relation:'+',note:'待驗證'},{source:'c',target:'a',relation:'+',note:'待驗證'}]}},
{id:'exchange',name:'交換圖',group:'視覺化思考',engine:'echarts',purpose:'標示人、資訊、物品或金錢的交換方向與內容。',data:{nodes:[{id:'a',name:'學生'},{id:'b',name:'學習平台'},{id:'c',name:'教師'}],links:[{source:'a',target:'b',relation:'提交練習'},{source:'b',target:'a',relation:'提供回饋'},{source:'c',target:'b',relation:'設計題目'},{source:'b',target:'c',relation:'回報學習紀錄'}]}},
{id:'why',name:'深挖圖 / Why 分析',group:'視覺化思考',engine:'echarts',purpose:'逐層追問原因，並標示證據；不能把推測自動當成根因。',data:{root:{name:'問題：報告延遲',children:[{name:'為何？資料整理未完成',children:[{name:'為何？來源格式不一致',children:[{name:'待驗證：缺少統一模板'}]}]},{name:'其他可能：時間估計不足'}]}}},
{id:'argument',name:'結論—理由—證據圖',group:'視覺化思考',engine:'echarts',purpose:'先呈現主張，再列理由與證據；階層排版不保證 MECE 或論證正確。',data:{root:{name:'主張：採用統一筆記格式',children:[{name:'理由一：方便查找',children:[{name:'證據：補入查找時間比較'}]},{name:'理由二：便於複習',children:[{name:'證據：補入使用者測試'}]}]}}},
{id:'matrix',name:'2×2 比較矩陣',group:'視覺化思考',engine:'echarts',purpose:'使用有明確定義的兩條尺度定位項目，分界值可自行設定。',data:{x_name:'投入成本',y_name:'預期效益',x_min:0,x_max:10,y_min:0,y_max:10,x_mid:5,y_mid:5,points:[{name:'方案 A',x:3,y:8},{name:'方案 B',x:8,y:7},{name:'方案 C',x:2,y:3}]}},
{id:'venn',name:'重疊圖 / 文氏圖',group:'視覺化思考',engine:'native',purpose:'支援兩組或三組集合，依相同文字元素計算交集；圓形面積不表示數量。',data:{sets:[{name:'課程 A',items:['資料分析','溝通','規劃']},{name:'課程 B',items:['資料分析','程式設計','規劃']},{name:'課程 C',items:['規劃','設計']}] }},
{id:'pyramid',name:'層級金字塔',group:'視覺化思考',engine:'native',purpose:'呈現願景、目標到行動的上下層級；三角形面積不是數量編碼。',data:{levels:[{title:'願景',text:'理解並應用所學'},{title:'目標',text:'能用自己的話解釋概念'},{title:'策略',text:'提取練習、回饋與間隔複習'},{title:'行動',text:'每週完成練習並檢查錯誤'}]}},
{id:'fishbone',name:'魚骨圖 / 原因分析',group:'視覺化思考',engine:'native',purpose:'整理可能原因，分支不是已驗證的根因；可使用人、機、料、法、環等分類。',data:{effect:'報告品質不穩定',causes:[{category:'人',items:['分工不清','經驗不足']},{category:'方法',items:['缺少檢核表','引用格式不一致']},{category:'工具',items:['檔案版本混亂']},{category:'資料',items:['來源不足']},{category:'環境',items:['討論時間不足']},{category:'衡量',items:['評分標準不明']}]}}
);
const NOTE_DEFS=[
['bullet','任務子彈筆記',[['願景與成果',['□ 定義本週可完成的成果']],['下一步行動',['□ 完成第一份練習','○ 討論研究題目']],['筆記與回顧',['● 記錄重要發現','回顧：哪些任務需要遷移？']]],'通用任務筆記模板；符號和任務架構可自行調整。'],
['problem_note','問題解決筆記',[['事實與問題',['目前觀察到什麼？','哪些只是推測？']],['假設與驗證',['提出可檢驗的解釋','需要哪些資料？']],['結論與行動',['一張圖說清楚一個主張','決定下一步與負責人']]],'整理事實、假設、驗證與行動；不聲稱是特定公司的官方模板。'],
['zettel','卡片盒筆記',[['文獻卡',['記錄來源與頁碼','以自己的話摘要']],['永久卡',['只聚焦一個清楚主張','寫出理由、例子與限制']],['連結與問題',['連到哪些既有概念？','有哪些相反觀點？']]],'卡片盒用於連結與發展想法；與問答式記憶卡分開呈現。'],
['flashcard','提取練習卡',[['問題面',['什麼是有限理性？','先嘗試回答，再查看答案']],['答案面',['決策受資訊、時間與認知能力限制']],['回饋與複習',['核對遺漏內容','安排下次複習時間']]],'可輸出問答卡版面；本版不包含自動排程或間隔重複演算法。'],
['reflection','反思與行動筆記',[['為什麼會這樣？',['記錄事件、可能原因與證據']],['我是怎麼想的？',['區分觀察、感受與解釋']],['我想改變什麼？',['寫出可執行的小步驟','設定回顧時間']]],'通用反思架構，避免把推論當成事實。'],
['three_layer','三層筆記',[['行動層',['明確下一步、時間與成果']],['構思層',['問題、想法、假設與註解']],['封存層',['原始資料摘要與來源連結']]],'把行動、思考與參考資料分層保存。'],
['three_point','三重點整理',[['重點一',['核心概念與定義']],['重點二',['範例與反例']],['重點三',['應用情境與待解問題']]],'每頁標題、三項重點與圖解的通用模板；非特定書籍的逐字重製。']
];
for(const [id,name,sections,purpose]of NOTE_DEFS)RESEARCH_CATALOG.push({id,name,group:'筆記方法',engine:'native',purpose,data:{sections:sections.map(([heading,items])=>({heading,items}))}});
const THINK_IDS=new Set(['concept','causal','exchange','why','argument','matrix','venn','pyramid','fishbone',...NOTE_DEFS.map(n=>n[0])]);
const oldResearchValidate=validateResearch;
validateResearch=function(doc){if(!THINK_IDS.has(doc?.type))return oldResearchValidate(doc);if(doc.version!=='1.0'||typeof doc.title!=='string'||!doc.title.trim()||!doc.data)throw Error('需要 version、title、data。');for(const k of ['title','subtitle','caption','source','x_label','y_label'])if(doc[k]!==undefined&&(typeof doc[k]!=='string'||doc[k].length>2000))throw Error(k+' 需為 2000 字內文字。');const d=doc.data;const text=(s,max=100)=>{if(typeof s!=='string'||!s.trim()||Array.from(s).length>max)throw Error('文字欄位不能留空或超過 '+max+' 字。');};
if(['concept','causal','exchange'].includes(doc.type)){oldResearchValidate({...doc,type:'network'});if(d.links.length>500)throw Error('連線最多 500 條。');d.links.forEach(l=>{text(l.relation,40);if(doc.type==='causal'&&!['+','-','−'].includes(l.relation))throw Error('因果循環連線需標示 + 或 −。');});}
if(['why','argument'].includes(doc.type))oldResearchValidate({...doc,type:'tree'});
if(doc.type==='matrix'){['x_min','x_max','y_min','y_max','x_mid','y_mid'].forEach(k=>finite(d[k],k));if(!(d.x_min<d.x_mid&&d.x_mid<d.x_max&&d.y_min<d.y_mid&&d.y_mid<d.y_max))throw Error('分界需介於最小與最大值之間。');text(d.x_name);text(d.y_name);if(!Array.isArray(d.points)||!d.points.length||d.points.length>100)throw Error('需要 1–100 個 points。');d.points.forEach(p=>{text(p.name,40);finite(p.x,'x');finite(p.y,'y');if(p.x<d.x_min||p.x>d.x_max||p.y<d.y_min||p.y>d.y_max)throw Error('點超出座標範圍。');});}
if(doc.type==='venn'){if(!Array.isArray(d.sets)||d.sets.length<2||d.sets.length>3)throw Error('請提供兩組或三組 sets。');d.sets.forEach(s=>{text(s.name,20);if(!Array.isArray(s.items)||s.items.length>12)throw Error('每組最多 12 個文字元素。');s.items.forEach(v=>text(v,12));});}
if(doc.type==='pyramid'){if(!Array.isArray(d.levels)||d.levels.length<2||d.levels.length>6)throw Error('請提供 2–6 層 levels。');d.levels.forEach(l=>{text(l.title,20);text(l.text,50);});}
if(doc.type==='fishbone'){text(d.effect,30);if(!Array.isArray(d.causes)||d.causes.length<2||d.causes.length>6)throw Error('請提供 2–6 個原因分類。');d.causes.forEach(c=>{text(c.category,15);if(!Array.isArray(c.items)||c.items.length>3)throw Error('每個分類最多 3 個原因。');c.items.forEach(v=>text(v,24));});}
if(NOTE_DEFS.some(n=>n[0]===doc.type)){if(!Array.isArray(d.sections)||d.sections.length<1||d.sections.length>6)throw Error('需要 1–6 個 sections。');d.sections.forEach(s=>{text(s.heading,30);if(!Array.isArray(s.items)||s.items.length>5)throw Error('每區最多 5 項。');s.items.forEach(i=>text(i,80));});}return RESEARCH_CATALOG.find(x=>x.id===doc.type);};
const oldResearchOption=researchOption;
researchOption=function(doc,theme){if(['concept','causal','exchange'].includes(doc.type)){validateResearch(doc);const o=oldResearchOption({...doc,type:'network'},theme);o.series[0].links=doc.data.links.map(l=>({source:l.source,target:l.target,relation:l.relation,lineStyle:{curveness:.22}}));o.series[0].edgeLabel={show:true,fontSize:12,formatter:p=>p.data.relation};o.series[0].force={repulsion:850,edgeLength:200};return o;}if(['why','argument'].includes(doc.type))return oldResearchOption({...doc,type:'tree'},theme);if(doc.type==='matrix'){validateResearch(doc);const d=doc.data;return {animation:false,grid:{left:80,right:60,top:50,bottom:70},xAxis:{type:'value',min:d.x_min,max:d.x_max,name:d.x_name,nameLocation:'middle',nameGap:35},yAxis:{type:'value',min:d.y_min,max:d.y_max,name:d.y_name,nameLocation:'middle',nameGap:45},series:[{type:'scatter',symbolSize:14,data:d.points.map(p=>({name:p.name,value:[p.x,p.y]})),label:{show:true,position:'top',formatter:'{b}'},markLine:{silent:true,symbol:'none',label:{show:false},data:[{xAxis:d.x_mid},{yAxis:d.y_mid}]}}]};}return oldResearchOption(doc,theme);};
function vennRegions(sets){const all=new Set(sets.flatMap(s=>s.items)),regions={};for(const item of all){const key=sets.map((s,i)=>s.items.includes(item)?String(i):'').join('');(regions[key]??=[]).push(item);}return regions;}
function nativeDiagram(doc,width,height,theme='research'){validateResearch(doc);const style=VCStyle.state(),p=theme==='mono'?[style.fg,style.muted]:VCStyle.palette(),NS='http://www.w3.org/2000/svg';const make=(tag,attrs={},text)=>{const n=document.createElementNS(NS,tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;return n;};const svg=make('svg',{xmlns:NS,width,height,viewBox:`0 0 ${width} ${height}`});svg.append(make('rect',{width,height,fill:style.bg}));const line=(x1,y1,x2,y2,c=p[0],w=2)=>svg.append(make('line',{x1,y1,x2,y2,stroke:c,'stroke-width':w}));function text(str,x,y,max=18,size=14,anchor='middle'){const chunks=String(str).split('\n').flatMap(l=>{const a=Array.from(l),r=[];while(a.length)r.push(a.splice(0,max).join(''));return r.length?r:[''];});const t=make('text',{x,y,fill:style.fg,'font-family':'Arial, Noto Sans TC, sans-serif','font-size':size,'text-anchor':anchor});chunks.forEach((c,i)=>t.append(make('tspan',{x,dy:i?size*1.45:0},c)));svg.append(t);return chunks.length;}
const d=doc.data;
if(doc.type==='venn'){const three=d.sets.length===3,cx=width/2,cy=height/2,r=Math.min(width*.21,height*.29),centers=three?[[cx-r*.6,cy-r*.25],[cx+r*.6,cy-r*.25],[cx,cy+r*.65]]:[[cx-r*.55,cy],[cx+r*.55,cy]];centers.forEach(([x,y],i)=>{svg.append(make('circle',{cx:x,cy:y,r,fill:p[i],'fill-opacity':.13,stroke:p[i],'stroke-width':3}));text(d.sets[i].name,x,y-r-12,15,15);});const regions=vennRegions(d.sets),spots=three?{'0':[cx-r*.95,cy-r*.3],'1':[cx+r*.95,cy-r*.3],'2':[cx,cy+r*1.1],'01':[cx,cy-r*.55],'02':[cx-r*.45,cy+r*.4],'12':[cx+r*.45,cy+r*.4],'012':[cx,cy]}:{'0':[cx-r*.95,cy],'1':[cx+r*.95,cy],'01':[cx,cy]};for(const [key,items]of Object.entries(regions)){const spot=spots[key];if(spot)text(items.length?items.join('、'):'∅',...spot,three?7:10,11);}text('面積不代表元素數量；交集依完全相同的文字比對。',cx,height-12,70,11);}
if(doc.type==='pyramid'){const top=25,bottom=height-25,left=30,cx=width*.27,step=(bottom-top)/d.levels.length;d.levels.forEach((level,i)=>{const y1=top+i*step,y2=y1+step,x1=cx-(cx-left)*i/d.levels.length,x2=cx-(cx-left)*(i+1)/d.levels.length;svg.append(make('polygon',{points:`${x1},${y1} ${2*cx-x1},${y1} ${2*cx-x2},${y2} ${x2},${y2}`,fill:p[i%p.length],'fill-opacity':.2,stroke:p[i%p.length],'stroke-width':2}));const yy=(y1+y2)/2;line(2*cx-(x1+x2)/2,yy,width*.58,yy,p[i%p.length],1);text(level.title,width*.61,yy-8,25,15,'start');text(level.text,width*.61,yy+14,Math.floor(width*.35/12),12,'start');});}

if(doc.type==='fishbone'){const mid=height/2,end=width-180;line(35,mid,end,mid,p[0],3);svg.append(make('rect',{x:end,y:mid-55,width:165,height:110,rx:10,fill:style.surface,stroke:p[0],'stroke-width':2}));text(d.effect,end+82,mid-10,10,14);const per=Math.ceil(d.causes.length/2);d.causes.forEach((c,i)=>{const up=i%2===0,x=145+Math.floor(i/2)*(end-175)/per,y=up?65:height-65;line(x,y,x+65,mid,p[i%p.length]);text(c.category,x,y+(up?-18:28),12,15);c.items.forEach((item,j)=>{const yy=y+(mid-y)*(j+1)/(c.items.length+1),xx=x+65*(j+1)/(c.items.length+1);line(xx-35,yy,xx,yy,p[i%p.length],1);text(item,xx-7,yy-8,14,11,'end');});});}
if(d.sections){const count=d.sections.length,cols=Math.min(3,count),rows=Math.ceil(count/cols),gap=18,pad=20,cw=(width-pad*2-gap*(cols-1))/cols,ch=(height-pad*2-gap*(rows-1))/rows;d.sections.forEach((s,i)=>{const x=pad+(i%cols)*(cw+gap),y=pad+Math.floor(i/cols)*(ch+gap);svg.append(make('rect',{x,y,width:cw,height:ch,rx:10,fill:style.surface,stroke:p[i%p.length],'stroke-width':2}));const max=Math.max(8,Math.floor((cw-32)/13)),all=s.items.map(t=>'• '+t),totalLines=all.reduce((n,t)=>n+Math.ceil(Array.from(t).length/max),0);const font=Math.max(9,Math.min(13,(ch-78)/Math.max(1,totalLines)/1.5));text(s.heading,x+16,y+30,max,15,'start');line(x+16,y+44,x+cw-16,y+44,p[i%p.length],1);let yy=y+68;for(const item of all){const used=text(item,x+16,yy,max,font,'start');yy+=used*font*1.45+8;}});}
return svg;}
