/* IE/time calculations: explicit units, formulas, validation and report tables. */
(()=>{'use strict';const all=[];function add(id,label,desc,data){all.push({id,label,desc,data:{type:id,title:label+'｜合成範例',...data}});}
add('labor_productivity','勞動生產力比較','產出 ÷ 人數與工時，計算每人時產出',{periods:[{title:'改善前',output:480,workers:4,hours:8},{title:'改善後',output:600,workers:4,hours:8}],output_unit:'件'});
add('oee_calculator','OEE 設備綜合效率','時間稼動率 × 性能效率 × 良品率',{planned_minutes:480,stop_minutes:60,ideal_cycle_seconds:30,total_count:700,good_count:665});
add('line_balance_efficiency','產線平衡效率','各工作站負荷、空閒與平衡效率',{station_seconds:[45,50,40,55],cycle_seconds:60});
add('efficiency_effectiveness','效率與效能比較','效率看投入產出，效能看達成目標',{planned_input:40,actual_input:36,planned_output:100,actual_output:90,input_unit:'人時',output_unit:'件'});
add('takt_time_calculator','需求節拍與週期比較','淨可用時間 ÷ 需求，檢查目前週期',{net_minutes:420,demand:360,actual_cycle_seconds:65});
add('workload_time_estimate','工作量與總時間估算','每次分鐘 × 次數，再加準備與緩衝',{tasks:[{title:'閱讀講義',minutes_each:25,repetitions:4},{title:'解題',minutes_each:8,repetitions:12},{title:'整理報告',minutes_each:45,repetitions:1}],setup_minutes:15,buffer_percent:15});
add('capacity_load','產能負荷與缺口','總加工需求 ÷ 淨可用產能',{jobs:[{title:'產品 A',quantity:50,minutes_per_unit:4},{title:'產品 B',quantity:30,minutes_per_unit:6}],available_minutes:360});
add('workday_calendar_plan','工作日計畫日曆','依每日分鐘自動分配任務，跳過休假日',{start_date:'2026-10-09',daily_minutes:120,workdays:[0,1,2,3,4],excluded_dates:['2026-10-12'],tasks:[{title:'需求訪談整理',minutes:180},{title:'原型製作',minutes:240},{title:'測試與報告',minutes:210}]});
window.VC_LEARNING_TEMPLATES.push(...all);CHARTS.push(...all.map(t=>[t.id,t.label]));const base=chartConfig;
const fail=s=>{throw Error(s);};function num(n,k,min=0,max=1e9){if(typeof n!=='number'||!Number.isFinite(n)||n<min||n>max)fail(k+' 需為 '+min+'–'+max+' 的有限數字。');}function positive(n,k){num(n,k,1e-6);}function integer(n,k,min=0){num(n,k,min);if(!Number.isInteger(n))fail(k+' 需為整數。');}function array(a,k,max=40){if(!Array.isArray(a)||!a.length||a.length>max)fail(k+' 需為 1–'+max+' 個項目。');return a;}function text(s,k){if(typeof s!=='string'||!s.trim()||s.length>120)fail(k+' 使用 1–120 字。');}function date(s){if(typeof s!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(s))fail('日期格式使用 YYYY-MM-DD。');const n=Date.parse(s+'T00:00:00Z');if(!Number.isFinite(n)||new Date(n).toISOString().slice(0,10)!==s)fail('日期不存在。');return n;}
function calculate(d){let rows=[],formula='',labels=[],values=[],unit='',schedule=[];
if(d.type==='labor_productivity'){text(d.output_unit,'output_unit');array(d.periods,'periods',20).forEach(s=>{text(s.title,'title');num(s.output,'output');integer(s.workers,'workers',1);positive(s.hours,'hours');const input=s.workers*s.hours,p=s.output/input;rows.push([s.title,s.output+' '+d.output_unit,input.toFixed(2)+' 人時',p.toFixed(3)+' '+d.output_unit+'/人時']);labels.push(s.title);values.push(p);});formula='生產力 = 產出 ÷（人數 × 每人工時）；各期需使用相同產出定義與單位。';unit=d.output_unit+'/人時';}
else if(d.type==='oee_calculator'){positive(d.planned_minutes,'planned_minutes');num(d.stop_minutes,'stop_minutes');positive(d.ideal_cycle_seconds,'ideal_cycle_seconds');integer(d.total_count,'total_count',1);integer(d.good_count,'good_count');const run=d.planned_minutes-d.stop_minutes;if(run<=0)fail('停機時間必須小於計畫生產時間。');if(d.good_count>d.total_count)fail('良品數不可超過總生產數。');const a=run/d.planned_minutes,p=d.ideal_cycle_seconds*d.total_count/(run*60),q=d.good_count/d.total_count;if(p>1+1e-9)fail('性能效率超過 100%，請檢查理想週期、單位與總件數。');labels=['時間稼動率 A','性能效率 P','良品率 Q','OEE'];values=[a,p,q,a*p*q].map(v=>v*100);rows=labels.map((s,i)=>[s,values[i].toFixed(2)+'%',i===0?run+' / '+d.planned_minutes+' 分':i===1?d.ideal_cycle_seconds+' 秒 × '+d.total_count+' / '+(run*60)+' 秒':i===2?d.good_count+' / '+d.total_count:'A × P × Q']);formula='A = 運轉時間/計畫時間；P = 理想週期×總件數/運轉時間；Q = 良品/總件數；OEE = A×P×Q。';unit='%';}
else if(d.type==='line_balance_efficiency'){array(d.station_seconds,'station_seconds',30).forEach(s=>num(s,'station_seconds'));positive(d.cycle_seconds,'cycle_seconds');if(d.station_seconds.some(s=>s>d.cycle_seconds))fail('單一工作站負荷不可超過指定週期；請先調整分配或週期。');const total=d.station_seconds.reduce((a,b)=>a+b,0),available=d.station_seconds.length*d.cycle_seconds,eff=total/available;labels=d.station_seconds.map((_,i)=>'站 '+(i+1));values=d.station_seconds;rows=d.station_seconds.map((s,i)=>[labels[i],s.toFixed(2)+' 秒',(d.cycle_seconds-s).toFixed(2)+' 秒']);rows.push(['總工作內容',total.toFixed(2)+' 秒','平衡效率 '+(eff*100).toFixed(2)+'%'],['每週期總空閒',(available-total).toFixed(2)+' 秒','平衡損失 '+((1-eff)*100).toFixed(2)+'%']);formula='平衡效率 = Σ工作站負荷 /（工作站數 × 週期）；圖上虛線為週期。負荷需為已分配的站總工時。';unit='秒';}
else if(d.type==='efficiency_effectiveness'){positive(d.planned_input,'planned_input');positive(d.actual_input,'actual_input');positive(d.planned_output,'planned_output');num(d.actual_output,'actual_output');text(d.input_unit,'input_unit');text(d.output_unit,'output_unit');const expected=d.planned_output/d.planned_input,actual=d.actual_output/d.actual_input;labels=['投入產出效率指數','目標達成效能'];values=[actual/expected*100,d.actual_output/d.planned_output*100];rows=[['計畫生產力',expected.toFixed(3),d.output_unit+'/'+d.input_unit],['實際生產力',actual.toFixed(3),d.output_unit+'/'+d.input_unit],...labels.map((s,i)=>[s,values[i].toFixed(2)+'%',i===0?'實際生產力 / 計畫生產力':'實際產出 / 計畫產出'])];formula='本表定義：效率指數 =（實際產出/實際投入）÷（計畫產出/計畫投入）；效能 = 實際產出/目標產出。可超過 100%。';unit='%';}
else if(d.type==='takt_time_calculator'){positive(d.net_minutes,'net_minutes');integer(d.demand,'demand',1);positive(d.actual_cycle_seconds,'actual_cycle_seconds');const takt=d.net_minutes*60/d.demand,capacity=Math.floor(d.net_minutes*60/d.actual_cycle_seconds);labels=['需求節拍','目前實際週期'];values=[takt,d.actual_cycle_seconds];rows=[['需求節拍',takt.toFixed(3)+' 秒/件','淨可用分鐘 × 60 / 需求'],['理論產能',capacity+' 件','假設全時運轉、無其他損失'],['需求缺口',Math.max(0,d.demand-capacity)+' 件',d.actual_cycle_seconds<=takt?'週期符合需求節拍':'目前週期慢於需求節拍']];formula='Takt = 淨可用時間 / 同期間需求；理論產能 = floor(淨可用秒數 / 實際週期)。節拍不是實測週期。';unit='秒/件';}
else if(d.type==='workload_time_estimate'){array(d.tasks,'tasks').forEach(s=>{text(s.title,'task title');num(s.minutes_each,'minutes_each');integer(s.repetitions,'repetitions',1);labels.push(s.title);values.push(s.minutes_each*s.repetitions);});num(d.setup_minutes,'setup_minutes');num(d.buffer_percent,'buffer_percent',0,200);const work=values.reduce((a,b)=>a+b,0),baseTime=work+d.setup_minutes,buffer=baseTime*d.buffer_percent/100,total=baseTime+buffer;rows=d.tasks.map((s,i)=>[s.title,s.minutes_each+' × '+s.repetitions,values[i].toFixed(2)+' 分']);rows.push(['準備時間','額外固定投入',d.setup_minutes.toFixed(2)+' 分'],['緩衝','(工作+準備) × '+d.buffer_percent+'%',buffer.toFixed(2)+' 分'],['合計',total.toFixed(2)+' 分',(total/60).toFixed(2)+' 小時']);formula='總分鐘 =（Σ每次分鐘×次數 + 準備分鐘）×（1 + 緩衝百分比/100）；為順序執行估算。';unit='分鐘';}
else if(d.type==='capacity_load'){array(d.jobs,'jobs').forEach(s=>{text(s.title,'job title');integer(s.quantity,'quantity');positive(s.minutes_per_unit,'minutes_per_unit');labels.push(s.title);values.push(s.quantity*s.minutes_per_unit);});positive(d.available_minutes,'available_minutes');const required=values.reduce((a,b)=>a+b,0);rows=d.jobs.map((s,i)=>[s.title,s.quantity+' × '+s.minutes_per_unit+' 分/件',values[i].toFixed(2)+' 分']);rows.push(['總需求',required.toFixed(2)+' 分','負荷 '+(required/d.available_minutes*100).toFixed(2)+'%'],['淨可用時間',d.available_minutes.toFixed(2)+' 分','時間缺口 '+Math.max(0,required-d.available_minutes).toFixed(2)+' 分']);formula='需求時間 = Σ數量×每件加工分鐘；負荷率 = 需求/淨可用分鐘。模型為單一共用資源，不包含換線與平行加工。';unit='分鐘';}
else if(d.type==='workday_calendar_plan'){let ms=date(d.start_date);positive(d.daily_minutes,'daily_minutes');if(d.daily_minutes>1440)fail('daily_minutes 不可超過 1440。');array(d.workdays,'workdays',7).forEach(s=>integer(s,'workdays',0));if(d.workdays.some(s=>s>6)||new Set(d.workdays).size!==d.workdays.length)fail('workdays 使用不重複的 0（週一）到 6（週日）。');if(!Array.isArray(d.excluded_dates)||d.excluded_dates.length>100)fail('excluded_dates 需為最多 100 個日期的陣列。');d.excluded_dates.forEach(date);array(d.tasks,'tasks',30).forEach(s=>{text(s.title,'task title');positive(s.minutes,'minutes');});const excluded=new Set(d.excluded_dates),total=d.tasks.reduce((n,s)=>n+s.minutes,0);if(total/d.daily_minutes>200)fail('計畫超過 200 個工作日，請拆分。');let used=0,iterations=0;const iso=()=>new Date(ms).toISOString().slice(0,10);function next(){ms+=86400000;used=0;}function eligible(){while(!d.workdays.includes((new Date(ms).getUTCDay()+6)%7)||excluded.has(iso())){if(++iterations>2000)fail('找不到可用工作日。');next();}}
for(const task of d.tasks){let remaining=task.minutes;while(remaining>1e-7){eligible();if(used>=d.daily_minutes-1e-7){next();continue;}const amount=Math.min(remaining,d.daily_minutes-used);schedule.push({date:iso(),title:task.title,minutes:amount});used+=amount;remaining-=amount;if(schedule.length>1000)fail('排程片段過多。');}}
const days=[...new Set(schedule.map(s=>s.date))];labels=days;values=days.map(day=>schedule.filter(s=>s.date===day).reduce((n,s)=>n+s.minutes,0));rows=schedule.map(s=>[s.date,s.title,s.minutes.toFixed(2)+' 分']);rows.push(['總投入',total.toFixed(2)+' 分',(total/60).toFixed(2)+' 小時'],['工作日／曆日',days.length+' 工作日',(Math.round((date(days.at(-1))-date(d.start_date))/86400000)+1)+' 曆日'],['預計完成日',days.at(-1),'最後一天使用 '+used.toFixed(2)+' 分']);formula='按輸入順序分配總分鐘，每日不超過 daily_minutes；跳過非工作日與 excluded_dates。無平行任務、提醒或自動國定假日。';unit='分鐘';}
return {rows,formula,labels,values,unit,schedule};}
chartConfig=function(d){if(!all.some(t=>t.id===d?.type))return base(d);text(d.title,'title');const r=calculate(d),E=s=>safeText(String(s)),fmt=s=>{const a=Array.from(String(s)),out=[];while(a.length)out.push(E(a.splice(0,46).join('')));return out.join('<br>');},headers={labor_productivity:['期間','產出','投入','生產力'],oee_calculator:['指標','結果','代入公式'],line_balance_efficiency:['工作站／指標','負荷／結果','空閒／說明'],efficiency_effectiveness:['指標','結果','定義／單位'],takt_time_calculator:['指標','結果','說明'],workload_time_estimate:['工作項目','計算','時間'],capacity_load:['項目','計算','需求／負荷'],workday_calendar_plan:['日期／彙總','任務／结果','時間／說明']}[d.type],values=headers.map((_,i)=>r.rows.map(row=>E(row[i]??'')));const traces=[{type:'bar',x:r.labels.map(E),y:r.values,xaxis:'x',yaxis:'y',hovertemplate:'%{x}<br>%{y:.3f} '+E(r.unit)+'<extra></extra>'},{type:'table',domain:{y:[0,.55]},header:{values:headers,height:36,font:{size:13},align:'left'},cells:{values,height:34,font:{size:12},align:'left'}}];const layout={title:{text:E(d.title)+'<br><sup>'+E(r.rows.at(-1).join('｜'))+'</sup>'},showlegend:false,xaxis:{domain:[0,1],anchor:'y',automargin:true,tickfont:{size:11}},yaxis:{domain:[.72,1],anchor:'x',title:{text:E(r.unit)},rangemode:'tozero',automargin:true},annotations:[{xref:'paper',yref:'paper',x:0,y:.64,xanchor:'left',yanchor:'middle',align:'left',text:fmt(r.formula),showarrow:false,font:{size:12}}],margin:{t:110,l:75,r:35,b:35}};if(d.type==='line_balance_efficiency')layout.shapes=[{type:'line',xref:'paper',yref:'y',x0:0,x1:1,y0:d.cycle_seconds,y1:d.cycle_seconds,line:{color:VCStyle.palette()[1],dash:'dash',width:2}}];return {traces,layout};};window.VCIECalculators={calculate,types:all.map(t=>t.id)};})();
