/* Process and time chart adapters. Coordinates and dates are validated locally. */
(()=>{'use strict';const base=chartConfig,types=new Set(window.VC_FLOWTIME.map(t=>t.id));
const fail=s=>{throw Error(s);};
function str(s,k){if(typeof s!=='string'||!s.trim()||s.length>200)fail(k+' 需為 1–200 字的文字。');}
function arr(a,k,max=40){if(!Array.isArray(a)||!a.length||a.length>max)fail(k+' 需為 1–'+max+' 個項目的陣列。');return a;}
function num(n,k,min=0,max=100000){if(typeof n!=='number'||!Number.isFinite(n)||n<min||n>max)fail(k+' 需為 '+min+'–'+max+' 的有限數字。');}
function date(s){str(s,'日期');if(!/^\d{4}-\d{2}-\d{2}$/.test(s))fail('日期使用 YYYY-MM-DD。');const ms=Date.parse(s+'T00:00:00Z');if(!Number.isFinite(ms)||new Date(ms).toISOString().slice(0,10)!==s)fail('日期不存在：'+s);return ms;}
function graph(nodes,rels){arr(nodes,'nodes');const ids=new Set();nodes.forEach(n=>{str(n.id,'id');str(n.title,'節點 title');if(ids.has(n.id))fail('id 不可重複。');ids.add(n.id);});if(!Array.isArray(rels)||rels.length>100)fail('連線需為最多 100 條的陣列。');rels.forEach(r=>{if(!ids.has(r.from)||!ids.has(r.to))fail('連線必須指向既有節點。');if(r.label!==undefined)str(r.label,'連線 label');});}
function validate(d){str(d.title,'title');const t=d.type;
 if(t==='swimlane'){arr(d.lanes,'lanes',8).forEach(v=>str(v,'lane'));graph(d.steps,d.links);d.steps.forEach(s=>{if(!Number.isInteger(s.lane)||s.lane<0||s.lane>=d.lanes.length)fail('lane 使用從 0 起算的泳道索引。');});}
 else if(t==='sequence_diagram'){arr(d.participants,'participants',8).forEach(s=>str(s,'participant'));arr(d.messages,'messages',40).forEach(m=>{str(m.text,'message text');if([m.from,m.to].some(v=>!Number.isInteger(v)||v<0||v>=d.participants.length)||m.from===m.to)fail('訊息端點需為不同的合法參與者索引。');});}
 else if(['state_machine','branching_flow'].includes(t)){graph(d.nodes,d.relations);if(t==='branching_flow')d.nodes.forEach(n=>{if(!Number.isInteger(n.level)||n.level<0||n.level>12)fail('level 需為 0–12 的整數。');});}
 else if(t==='parallel_flow')arr(d.stages,'stages',12).forEach(s=>{str(s.title,'stage title');arr(s.tasks,'tasks',8).forEach(x=>str(x,'task'));});
 else if(t==='loop_flow'){arr(d.steps,'steps',12).forEach(s=>str(s.title,'step title'));if([d.repeat_from,d.repeat_to].some(v=>!Number.isInteger(v)||v<0||v>=d.steps.length)||d.repeat_to>=d.repeat_from)fail('repeat_to 必須指向 repeat_from 之前的步驟。');str(d.repeat_label,'repeat_label');}
 else if(t==='input_output_flow'){arr(d.inputs,'inputs',10).forEach(s=>str(s,'input'));arr(d.outputs,'outputs',10).forEach(s=>str(s,'output'));str(d.process,'process');}
 else if(t==='data_flow'){[d.entities,d.processes,d.stores].forEach(a=>arr(a,'各類節點',12));graph([...d.entities,...d.processes,...d.stores],d.flows);}
 else if(t==='funnel_process'){arr(d.steps,'steps',15).forEach((s,i)=>{str(s.title,'step title');num(s.count,'count');if(i&&s.count>d.steps[i-1].count)fail('篩選流程的數量不可逐步增加。');});if(!d.steps[0].count)fail('第一階段 count 需大於 0。');}
 else if(t==='value_stream')arr(d.steps,'steps',12).forEach(s=>{str(s.title,'step title');num(s.process_minutes,'process_minutes');num(s.wait_minutes,'wait_minutes');});
 else if(t==='study_calendar'){if(typeof d.month!=='string'||!/^\d{4}-\d{2}$/.test(d.month))fail('month 使用 YYYY-MM。');date(d.month+'-01');const seen=new Set();arr(d.entries,'entries',31).forEach(e=>{date(e.date);num(e.value,'value');if(!e.date.startsWith(d.month+'-')||seen.has(e.date))fail('entries 日期需在指定月份內且不能重複。');seen.add(e.date);});}
 else if(['weekly_timetable','daily_timeblocks'].includes(t)){arr(d.blocks,'blocks',40).forEach(b=>{str(b.title,'block title');num(b.start,'start',0,24);num(b.end,'end',0,24);if(b.end<=b.start)fail('end 必須大於 start，跨午夜請拆開。');if(t==='weekly_timetable'&&(!Number.isInteger(b.day)||b.day<0||b.day>6))fail('day 是 0（週一）到 6（週日）。');});for(let i=0;i<d.blocks.length;i++)for(let j=0;j<i;j++){const a=d.blocks[i],b=d.blocks[j];if((t==='daily_timeblocks'||a.day===b.day)&&a.start<b.end&&b.start<a.end)fail('同一天的時間塊不可重疊。');}}
 else if(t==='milestone_timeline')arr(d.milestones,'milestones',30).forEach(m=>{date(m.date);str(m.title,'milestone title');});
 else if(t==='review_timeline')arr(d.sessions,'sessions',100).forEach(s=>{date(s.date);str(s.topic,'topic');if(!['done','planned'].includes(s.status))fail('status 使用 done 或 planned。');});
 else if(t==='countdown_plan'){date(d.exam_date);arr(d.tasks,'tasks',30).forEach(s=>{str(s.title,'task title');num(s.days_before,'days_before',0,365);num(s.duration,'duration',.01,365);if(s.duration>s.days_before)fail('duration 不可超過 days_before，以免排到考試後。');});}
 else if(t==='duration_comparison')arr(d.tasks,'tasks',30).forEach(s=>{str(s.title,'task title');num(s.minutes,'minutes');});
 else if(t==='cumulative_study')arr(d.sessions,'sessions',100).forEach(s=>{date(s.date);num(s.minutes,'minutes');});
 else if(t==='time_distribution'){arr(d.labels,'labels',20).forEach(s=>str(s,'label'));arr(d.minutes,'minutes',20).forEach(n=>num(n,'minutes'));if(d.labels.length!==d.minutes.length||!d.minutes.some(n=>n>0))fail('labels/minutes 需等長，且總時間大於 0。');}
 else if(t==='schedule_dependencies'){arr(d.tasks,'tasks',30);const ids=new Set(d.tasks.map(s=>s.id));if(ids.size!==d.tasks.length)fail('任務 id 不可重複。');d.tasks.forEach(s=>{str(s.id,'id');str(s.title,'task title');num(s.start,'start',0,365);num(s.duration,'duration',.01,365);if(!Array.isArray(s.depends)||s.depends.some(id=>!ids.has(id)||id===s.id))fail('depends 需指向其他已存在的任務。');});const map=new Map(d.tasks.map(s=>[s.id,s])),seen=new Set(),visiting=new Set();function visit(s){if(visiting.has(s.id))fail('任務依賴不可循環。');if(seen.has(s.id))return;visiting.add(s.id);s.depends.forEach(id=>{const p=map.get(id);visit(p);if(p.start+p.duration>s.start)fail('前置任務尚未完成：'+p.title+' → '+s.title);});visiting.delete(s.id);seen.add(s.id);}d.tasks.forEach(visit);}
}
chartConfig=function(d){if(!types.has(d?.type))return base(d);validate(d);const st=VCStyle.state(),pal=VCStyle.palette(),traces=[],shapes=[],annotations=[],E=s=>safeText(String(s??'')),C=i=>pal[i%pal.length];let xmin=Infinity,xmax=-Infinity,ymin=Infinity,ymax=-Infinity;const t=d.type;
 const wrap=(s,n=16)=>String(s).split('\n').map(line=>{const a=Array.from(line),out=[];while(a.length)out.push(E(a.splice(0,n).join('')));return out.join('<br>');}).join('<br>');
 function bounds(x,y,w=0,h=0){xmin=Math.min(xmin,x-w/2);xmax=Math.max(xmax,x+w/2);ymin=Math.min(ymin,y-h/2);ymax=Math.max(ymax,y+h/2);}
 function label(x,y,s,i=0){annotations.push({x,y,xref:'x',yref:'y',text:wrap(s),showarrow:false,font:{size:14,color:C(i)}});bounds(x,y,220,60);}
 function box(x,y,s,i=0,w=220){const h=Math.max(65,Math.ceil(Array.from(s).length/16)*23+30);shapes.push({type:'rect',x0:x-w/2,x1:x+w/2,y0:y-h/2,y1:y+h/2,line:{color:C(i),width:2},fillcolor:st.surface,layer:'below'});label(x,y,s,i);bounds(x,y,w,h);return {x,y,w,h};}
 function line(x0,y0,x1,y1,i=0,dash='solid'){shapes.push({type:'line',x0,y0,x1,y1,line:{color:C(i),width:2,dash},layer:'below'});bounds(x0,y0);bounds(x1,y1);}
 function arrow(a,b,s='',i=0){const horizontal=Math.abs(b.x-a.x)>Math.abs(b.y-a.y),dx=Math.sign(b.x-a.x),dy=Math.sign(b.y-a.y),ax=a.x+(horizontal?dx*(a.w||0)/2:0),ay=a.y+(!horizontal?dy*(a.h||0)/2:0),x=b.x-(horizontal?dx*(b.w||0)/2:0),y=b.y-(!horizontal?dy*(b.h||0)/2:0);annotations.push({x,y,ax,ay,xref:'x',yref:'y',axref:'x',ayref:'y',text:'',showarrow:true,arrowhead:2,arrowwidth:2,arrowcolor:C(i)});if(s)label((ax+x)/2,(ay+y)/2-28,s,i);}
 function timeLayout(extra={}){return {traces,layout:{title:{text:E(d.title)},showlegend:false,...extra}};}
 if(t==='swimlane'){const m=new Map();d.lanes.forEach((s,i)=>{label(-210,i*180,s,i);line(-90,i*180+85,d.steps.length*300,i*180+85,i,'dot');});d.steps.forEach((s,i)=>m.set(s.id,box(i*300,s.lane*180,s.title,s.lane)));d.links.forEach((r,i)=>arrow(m.get(r.from),m.get(r.to),r.label||'',i));}
 else if(t==='sequence_diagram'){d.participants.forEach((s,i)=>{box(i*360,0,s,i);line(i*360,50,i*360,150+d.messages.length*130,i,'dot');});d.messages.forEach((m,i)=>arrow({x:m.from*360,y:140+i*130},{x:m.to*360,y:140+i*130},m.text,i));}
 else if(t==='state_machine'){const m=new Map(),radius=Math.max(280,d.nodes.length*55);d.nodes.forEach((n,i)=>{const a=2*Math.PI*i/d.nodes.length-Math.PI/2;m.set(n.id,box(Math.cos(a)*radius,Math.sin(a)*radius,n.title,i));});d.relations.forEach((r,i)=>arrow(m.get(r.from),m.get(r.to),r.label||'',i));}
 else if(t==='branching_flow'){const levels=new Map(),m=new Map();d.nodes.forEach(n=>{if(!levels.has(n.level))levels.set(n.level,[]);levels.get(n.level).push(n);});[...levels.keys()].sort((a,b)=>a-b).forEach((lv,j)=>{const ns=levels.get(lv);ns.forEach((n,i)=>m.set(n.id,box((i-(ns.length-1)/2)*340,j*220,n.title,j)));});d.relations.forEach((r,i)=>arrow(m.get(r.from),m.get(r.to),r.label||'',i));}
 else if(t==='parallel_flow'){let prev=[];d.stages.forEach((s,i)=>{label(i*340,-200,s.title,i);const bs=s.tasks.map((v,j)=>box(i*340,(j-(s.tasks.length-1)/2)*170,v,i));prev.forEach(a=>bs.forEach(b=>arrow(a,b,'',i)));prev=bs;});}
 else if(t==='loop_flow'){const bs=d.steps.map((s,i)=>box(i*320,0,s.title,i));bs.slice(1).forEach((b,i)=>arrow(bs[i],b));const a=bs[d.repeat_from],b=bs[d.repeat_to];line(a.x,a.h/2,a.x,200,1,'dash');line(a.x,200,b.x,200,1,'dash');arrow({x:b.x,y:200},b,d.repeat_label,1);}
 else if(t==='input_output_flow'){const p=box(0,0,d.process,1,260);d.inputs.forEach((s,i)=>arrow(box(-440,(i-(d.inputs.length-1)/2)*160,s,0),p));d.outputs.forEach((s,i)=>arrow(p,box(440,(i-(d.outputs.length-1)/2)*160,s,2)));}
 else if(t==='data_flow'){const m=new Map();[d.entities,d.processes,d.stores].forEach((ns,c)=>ns.forEach((n,i)=>m.set(n.id,box(c*480,i*230,n.title,c))));d.flows.forEach((r,i)=>arrow(m.get(r.from),m.get(r.to),r.label||'',i));}
 else if(t==='funnel_process'){traces.push({type:'funnel',y:d.steps.map(s=>E(s.title)),x:d.steps.map(s=>s.count),textinfo:'value+percent initial',hovertemplate:'%{y}<br>%{x} '+E(d.unit||'項')+'<extra></extra>'});return timeLayout();}
 else if(t==='value_stream'){const bs=d.steps.map((s,i)=>box(i*340,0,s.title+'\n操作 '+s.process_minutes+' 分\n等待 '+s.wait_minutes+' 分',i,250));bs.slice(1).forEach((b,i)=>arrow(bs[i],b));label((d.steps.length-1)*170,200,'總操作 '+d.steps.reduce((n,s)=>n+s.process_minutes,0)+' 分；總等待 '+d.steps.reduce((n,s)=>n+s.wait_minutes,0)+' 分');}
 else if(t==='study_calendar'){const year=+d.month.slice(0,4),month=+d.month.slice(5,7),first=(new Date(d.month+'-01T00:00:00Z').getUTCDay()+6)%7,last=new Date(Date.UTC(year,month,0)).getUTCDate(),map=new Map(d.entries.map(e=>[e.date,e])),z=Array.from({length:6},()=>Array(7).fill(null)),hover=Array.from({length:6},()=>Array(7).fill('')),max=Math.max(1,...d.entries.map(e=>e.value));for(let day=1;day<=last;day++){const iso=d.month+'-'+String(day).padStart(2,'0'),e=map.get(iso),x=(first+day-1)%7,y=Math.floor((first+day-1)/7);z[y][x]=e?.value||0;hover[y][x]=iso+'<br>'+(e?e.value+' '+E(d.unit||'分鐘'):'未記錄')+(e?.note?'<br>'+E(e.note):'');annotations.push({x,y,xref:'x',yref:'y',text:String(day),showarrow:false,font:{size:16,color:e?.value>max*.6?VCStyle.inkOn(C(0)):st.fg}});}traces.push({type:'heatmap',x:[0,1,2,3,4,5,6],y:[0,1,2,3,4,5],z,zmin:0,zmax:max,xgap:4,ygap:4,customdata:hover,hoverongaps:false,hovertemplate:'%{customdata}<extra></extra>',colorbar:{title:{text:E(d.unit||'分鐘')}}});return timeLayout({annotations,xaxis:{tickvals:[0,1,2,3,4,5,6],ticktext:['一','二','三','四','五','六','日'],side:'top',range:[-.5,6.5]},yaxis:{range:[5.5,-.5],visible:false},hovermode:'closest'});}
 else if(t==='weekly_timetable'){d.blocks.forEach((b,i)=>{shapes.push({type:'rect',x0:b.day-.42,x1:b.day+.42,y0:b.start,y1:b.end,fillcolor:st.surface,line:{color:C(i),width:2}});annotations.push({x:b.day,y:(b.start+b.end)/2,text:wrap(b.title,6)+'<br>'+b.start+'–'+b.end,showarrow:false,font:{size:12,color:C(i)}});});traces.push({type:'scatter',x:[0],y:[0],mode:'markers',marker:{opacity:0},hoverinfo:'skip'});return timeLayout({shapes,annotations,xaxis:{tickvals:[0,1,2,3,4,5,6],ticktext:['週一','週二','週三','週四','週五','週六','週日'],range:[-.5,6.5],side:'top'},yaxis:{title:{text:'時（24 小時制）'},range:[Math.min(24,Math.ceil(Math.max(...d.blocks.map(b=>b.end)))+1),Math.max(0,Math.floor(Math.min(...d.blocks.map(b=>b.start)))-1)],dtick:1}});}
 else if(t==='daily_timeblocks'){traces.push({type:'bar',orientation:'h',y:d.blocks.map(b=>E(b.title)),x:d.blocks.map(b=>b.end-b.start),base:d.blocks.map(b=>b.start),customdata:d.blocks.map(b=>[b.start,b.end]),hovertemplate:'%{y}<br>%{customdata[0]}–%{customdata[1]} 時<extra></extra>'});return timeLayout({xaxis:{title:{text:'時（24 小時制）'},range:[0,24],dtick:2},yaxis:{autorange:'reversed'}});}
 else if(t==='milestone_timeline'){const ms=[...d.milestones].sort((a,b)=>date(a.date)-date(b.date));traces.push({type:'scatter',mode:'lines+markers+text',x:ms.map(m=>m.date),y:ms.map(()=>0),text:ms.map(m=>E(m.title)),textposition:ms.map((_,i)=>i%2?'bottom center':'top center'),marker:{size:14},hovertemplate:'%{x}<br>%{text}<extra></extra>'});return timeLayout({xaxis:{type:'date',title:{text:'日期'}},yaxis:{visible:false,range:[-1,1]}});}
 else if(t==='review_timeline'){const topics=[...new Set(d.sessions.map(s=>s.topic))];for(const status of ['planned','done']){const ss=d.sessions.filter(s=>s.status===status);if(ss.length)traces.push({type:'scatter',mode:'markers',name:status==='done'?'已完成':'計畫中',x:ss.map(s=>s.date),y:ss.map(s=>topics.indexOf(s.topic)),marker:{size:14,symbol:status==='done'?'circle':'circle-open'},hovertemplate:'%{x}<br>%{y}<extra>'+ (status==='done'?'已完成':'計畫中')+'</extra>'});}return timeLayout({showlegend:true,xaxis:{type:'date',title:{text:'日期'}},yaxis:{tickvals:topics.map((_,i)=>i),ticktext:topics.map(E),autorange:'reversed'}});}
 else if(t==='countdown_plan'){traces.push({type:'bar',orientation:'h',y:d.tasks.map(s=>E(s.title)),x:d.tasks.map(s=>s.duration),base:d.tasks.map(s=>-s.days_before),hovertemplate:'%{y}<br>持續 %{x} 天<extra></extra>'});return timeLayout({xaxis:{title:{text:'考前天數；0 = '+E(d.exam_date)},range:[-Math.max(...d.tasks.map(s=>s.days_before))-1,1]},yaxis:{autorange:'reversed'},shapes:[{type:'line',xref:'x',yref:'paper',x0:0,x1:0,y0:0,y1:1,line:{color:C(1),width:3}}]});}
 else if(t==='duration_comparison'){const tasks=[...d.tasks].sort((a,b)=>b.minutes-a.minutes);traces.push({type:'bar',orientation:'h',x:tasks.map(s=>s.minutes),y:tasks.map(s=>E(s.title)),text:tasks.map(s=>s.minutes+' 分'),textposition:'auto'});return timeLayout({xaxis:{title:{text:'分鐘'}},yaxis:{autorange:'reversed'}});}
 else if(t==='cumulative_study'){const totals=new Map();d.sessions.forEach(s=>totals.set(s.date,(totals.get(s.date)||0)+s.minutes));const dates=[...totals.keys()].sort();let sum=0;traces.push({type:'scatter',mode:'lines+markers',x:dates,y:dates.map(s=>sum+=totals.get(s)),fill:'tozeroy',hovertemplate:'%{x}<br>累積 %{y} 分鐘<extra></extra>'});return timeLayout({xaxis:{type:'date',title:{text:'日期'}},yaxis:{title:{text:'累積分鐘'},rangemode:'tozero'}});}
 else if(t==='time_distribution'){traces.push({type:'pie',labels:d.labels.map(E),values:d.minutes,hole:.55,hovertemplate:'%{label}<br>%{value} 分鐘（%{percent}）<extra></extra>'});return timeLayout({showlegend:true});}
 else if(t==='schedule_dependencies'){traces.push({type:'bar',orientation:'h',x:d.tasks.map(s=>s.duration),base:d.tasks.map(s=>s.start),y:d.tasks.map((_,i)=>i),customdata:d.tasks.map(s=>E(s.title)),hovertemplate:'%{customdata}<br>持續 %{x}<extra></extra>'});d.tasks.forEach((s,i)=>s.depends.forEach(id=>{const j=d.tasks.findIndex(p=>p.id===id),p=d.tasks[j];annotations.push({x:s.start,y:i,ax:p.start+p.duration,ay:j,xref:'x',yref:'y',axref:'x',ayref:'y',text:'',showarrow:true,arrowhead:2,arrowcolor:C(1),arrowwidth:2});}));return timeLayout({annotations,xaxis:{title:{text:E(d.unit||'天')},range:[0,Math.max(...d.tasks.map(s=>s.start+s.duration))+1]},yaxis:{tickvals:d.tasks.map((_,i)=>i),ticktext:d.tasks.map(s=>E(s.title)),autorange:'reversed'}});}
 traces.push({type:'scatter',x:[xmin],y:[ymin],mode:'markers',marker:{opacity:0,size:1},hoverinfo:'skip'});const rect=typeof document.getElementById==='function'?document.getElementById('plot')?.parentElement?.getBoundingClientRect?.():null,pw=Math.max(240,(rect?.width||1000)-130),ph=Math.max(260,(rect?.height||700)-235),gw=xmax-xmin+140,gh=ymax-ymin+140,scale=Math.min(pw/gw,ph/gh,1),rx=Math.max(gw,gh*pw/ph),ry=Math.max(gh,gw*ph/pw),cx=(xmin+xmax)/2,cy=(ymin+ymax)/2;annotations.forEach(a=>{if(a.font)a.font.size=Math.max(8,a.font.size*scale);});return timeLayout({annotations,shapes,dragmode:'pan',xaxis:{visible:false,range:[cx-rx/2,cx+rx/2]},yaxis:{visible:false,range:[cy+ry/2,cy-ry/2]}});
};
window.VCFlowTime={validate,types:[...types]};})();
