/* Six business templates: authored data, local validation, no AI/API calls. */
(()=>{'use strict';const all=[];function add(id,label,desc,data){all.push({id,label,desc,data:{type:id,title:label+'｜合成範例',...data}});}
add('business_model_canvas','商業模式畫布 BMC','九個區塊梳理價值、營運與收入',{key_partners:['校內合作單位','設備供應商'],key_activities:['需求訪談','原型開發'],key_resources:['開發團隊','測試設備'],value_propositions:['縮短作業等待','提供可追溯紀錄'],customer_relationships:['試用與回饋','持續支援'],channels:['校內試點','合作介紹'],customer_segments:['小型製造工作站'],cost_structure:['設備與開發成本','維護成本'],revenue_streams:['系統建置費','維護服務費']});
add('value_proposition_canvas','價值主張畫布 VPC','顧客任務痛點收穫與對應解方',{customer_jobs:['準時備妥零件'],pains:['尋料耗時','偶發錯料'],gains:['流程清楚','錯誤更少'],products_services:['視覺備料看板'],pain_relievers:['位置標示降低尋找時間'],gain_creators:['紀錄實際耗時以追蹤改善']});
add('pestel_analysis','PESTEL 環境分析','政治、經濟、社會、科技、環境與法律',{political:['政策補助可能支持改善'],economic:['設備預算有限'],social:['操作人員需要容易理解的介面'],technological:['感測器與開源工具可降低門檻'],environmental:['減少重工與材料浪費'],legal:['確認資料與設備使用規範']});
add('porter_five_forces','波特五力分析','競爭、進入者、替代品、供應商與買方',{rivalry:['既有軟體服務競爭'],new_entrants:['低成本工具降低進入門檻'],substitutes:['紙本紀錄或試算表'],supplier_power:['設備來源是否集中'],buyer_power:['客戶可選其他方案']});
add('aida_framework','AIDA 溝通架構','注意、興趣、渴望與行動',{attention:'每天有多少時間花在找零件？',interest:'展示一個工作站的尋料流程。',desire:'以實測比較改善前後差異，而非保證效果。',action:'邀請參加一週小規模試用並提供回饋。'});
add('okr_framework','OKR 目標與關鍵成果','以具體指標衡量目標進度',{objective:'改善本月專題驗證品質',key_results:[{title:'完成有效需求訪談',baseline:0,current:3,target:8,unit:'位',direction:'increase'},{title:'平均備料時間',baseline:60,current:52,target:40,unit:'秒',direction:'decrease'},{title:'完成驗證案例',baseline:0,current:2,target:5,unit:'件',direction:'increase'}]});
window.VC_LEARNING_TEMPLATES.push(...all);CHARTS.push(...all.map(t=>[t.id,t.label]));window.VC_BUSINESS_TYPES=['prep_framework','swot_analysis','tows_strategy','scqa_framework',...all.map(t=>t.id)];const base=chartConfig;
chartConfig=function(d){if(!all.some(t=>t.id===d?.type))return base(d);if(typeof d.title!=='string'||!d.title.trim()||d.title.length>200)throw Error('title 使用 1–200 字。');const E=s=>safeText(String(s)),st=VCStyle.state(),palette=VCStyle.palette(),annotations=[],shapes=[],traces=[];const wrap=(s,w=18)=>String(s).split('\n').map(part=>{const a=Array.from(part),lines=[];while(a.length)lines.push(E(a.splice(0,w).join('')));return lines.join('<br>');}).join('<br>');
function list(k){const a=d[k];if(!Array.isArray(a)||!a.length||a.length>4||a.some(s=>typeof s!=='string'||!s.trim()||s.length>80))throw Error(k+' 使用 1–4 個項目，每項 1–80 字。');return a.map(s=>'• '+s).join('\n');}
function text(k){if(typeof d[k]!=='string'||!d[k].trim()||d[k].length>240)throw Error(k+' 使用 1–240 字。');return d[k];}
const cards=[];function card(x,y,w,heading,body,i){const text='<b>'+E(heading)+'</b><br>'+wrap(body,Math.max(8,Math.floor((w-32)/14))),h=Math.max(110,text.split('<br>').length*23+36);cards.push({x,y,w,h,heading,body,text,i});return h;}
if(d.type==='business_model_canvas'){const keys=[['key_partners','關鍵夥伴'],['key_activities','關鍵活動'],['key_resources','關鍵資源'],['value_propositions','價值主張'],['customer_relationships','顧客關係'],['channels','通路'],['customer_segments','顧客族群']];let tallest=0;for(const [i,[k,name]]of keys.entries()){const pos=[[0,0],[220,0],[220,1],[440,0],[660,0],[660,1],[880,0]][i];tallest=Math.max(tallest,card(pos[0],pos[1],200,name,list(k),i));}cards.forEach((c,i)=>{if([0,3,6].includes(i))c.h=2*tallest+20;else{c.y=c.y*(tallest+20);c.h=tallest;}});const bottom=2*tallest+40;card(0,bottom,530,'成本結構',list('cost_structure'),7);card(550,bottom,530,'收入來源',list('revenue_streams'),8);}
else if(d.type==='value_proposition_canvas'){const keys=[['products_services','價值地圖｜產品與服務'],['customer_jobs','顧客輪廓｜顧客任務'],['pain_relievers','價值地圖｜痛點解方'],['pains','顧客輪廓｜痛點'],['gain_creators','價值地圖｜收穫創造'],['gains','顧客輪廓｜期望收穫']];let y=0;for(let i=0;i<6;i+=2){const h=Math.max(card(0,y,480,keys[i][1],list(keys[i][0]),i),card(500,y,480,keys[i+1][1],list(keys[i+1][0]),i+1));cards.slice(-2).forEach(c=>c.h=h);y+=h+20;}}
else if(d.type==='pestel_analysis'){const keys=[['political','P｜政治'],['economic','E｜經濟'],['social','S｜社會'],['technological','T｜科技'],['environmental','E｜環境'],['legal','L｜法律']];let y=0;for(let i=0;i<6;i+=3){const h=Math.max(...keys.slice(i,i+3).map(([k,n],j)=>card(j*320,y,300,n,list(k),i+j)));cards.slice(-3).forEach(c=>c.h=h);y+=h+20;}}
else if(d.type==='porter_five_forces'){const keys=[['supplier_power','供應商議價力'],['rivalry','既有競爭者競爭'],['buyer_power','買方議價力']];const incoming=card(340,0,320,'新進入者威脅',list('new_entrants'),0);let y=incoming+70;const h=Math.max(...keys.map(([k,n],i)=>card(i*340,y,320,n,list(k),i+1)));cards.slice(-3).forEach(c=>c.h=h);y+=h+70;card(340,y,320,'替代品威脅',list('substitutes'),4);shapes.push({type:'line',x0:500,x1:500,y0:incoming,y1:incoming+70,line:{color:palette[0],width:2}},{type:'line',x0:500,x1:500,y0:y-70,y1:y,line:{color:palette[4],width:2}});}
else if(d.type==='aida_framework'){let y=0;for(const [i,[k,n]]of [['attention','A｜注意'],['interest','I｜興趣'],['desire','D｜渴望'],['action','A｜行動']].entries())y+=card(0,y,900,n,text(k),i)+20;}
else{const objective=text('objective');if(!Array.isArray(d.key_results)||!d.key_results.length||d.key_results.length>8)throw Error('key_results 使用 1–8 個關鍵成果。');const rows=d.key_results.map(k=>{if(typeof k.title!=='string'||!k.title.trim()||k.title.length>120||typeof k.unit!=='string'||!k.unit.trim()||k.unit.length>20)throw Error('關鍵成果需要 title 與 unit。');if(['baseline','current','target'].some(key=>typeof k[key]!=='number'||!Number.isFinite(k[key])))throw Error('baseline/current/target 需為有限數字。');if(!['increase','decrease'].includes(k.direction)||(k.direction==='increase'?k.target<=k.baseline:k.target>=k.baseline))throw Error('target 須符合 direction 的增加或降低方向，且不能等於 baseline。');return {...k,progress:(k.current-k.baseline)/(k.target-k.baseline)*100};});const values=[rows.map(k=>wrap(k.title,18)),rows.map(k=>E(k.baseline+' '+k.unit)),rows.map(k=>E(k.current+' '+k.unit)),rows.map(k=>E(k.target+' '+k.unit)),rows.map(k=>k.progress.toFixed(1)+'%')];traces.push({type:'table',columnwidth:[3,1.4,1.4,1.4,1.2],header:{values:['關鍵成果','起點','目前','目標','相對進度'],height:42,align:'left',font:{size:15}},cells:{values,height:80,align:'left',font:{size:14}}});return {traces,layout:{title:{text:E(d.title)+'<br><sup>'+E(objective)+'</sup>'},margin:{t:110,l:35,r:35,b:65},annotations:[{xref:'paper',yref:'paper',x:0,y:-.08,text:'進度 =（目前 − 起點）／（目標 − 起點）；可低於 0% 或超過 100%。',showarrow:false,xanchor:'left',font:{size:11}}]}};}
const right=Math.max(...cards.map(c=>c.x+c.w)),bottom=Math.max(...cards.map(c=>c.y+c.h));const host=typeof document.getElementById==='function'?document.getElementById('plot')?.parentElement?.getBoundingClientRect?.():null,scale=Math.min(Math.max(240,(host?.width||1000)-90)/right,Math.max(240,(host?.height||700)-185)/bottom);
for(const c of cards){const color=palette[c.i%palette.length];shapes.push({type:'rect',x0:c.x,x1:c.x+c.w,y0:c.y,y1:c.y+c.h,line:{color,width:2},fillcolor:st.surface,layer:'below'});annotations.push({x:c.x+16,y:c.y+16,xref:'x',yref:'y',xanchor:'left',yanchor:'top',text:c.text,align:'left',showarrow:false,font:{size:Math.max(10,14*scale),color:st.fg},hovertext:E(c.body).replace(/\n/g,'<br>'),captureevents:true});}
traces.push({type:'scatter',x:[0],y:[0],mode:'markers',marker:{opacity:0},hoverinfo:'skip'});return {traces,layout:{title:{text:E(d.title)},annotations,shapes,showlegend:false,dragmode:'pan',xaxis:{visible:false,range:[-20,right+20]},yaxis:{visible:false,range:[bottom+20,-20]},margin:{t:85,l:25,r:25,b:30}}};};})();
