(()=>{'use strict';const all=[
{id:'prep_framework',label:'PREP 表達架構',desc:'觀點、理由、例子、重申觀點',data:{type:'prep_framework',title:'改善備料方式｜PREP 範例',point:'建議先試行定點備料。',reason:'降低作業員尋料與搬運的時間。',example:'合成試驗：每件尋料時間由 45 秒降到 30 秒。',restatement:'先在一個工作站試行，再用時間量測決定是否擴大。'}},
{id:'swot_analysis',label:'SWOT 分析矩陣',desc:'內部優劣勢與外部機會威脅',data:{type:'swot_analysis',title:'學習專題資源｜SWOT 範例',strengths:['具備基礎程式能力','可取得教師指導'],weaknesses:['實驗樣本較少','時間與預算有限'],opportunities:['可參與校內競賽','開源工具降低成本'],threats:['競賽時程可能衝突','資料取得存在不確定性']}},
{id:'tows_strategy',label:'TOWS 策略矩陣',desc:'把 SWOT 轉成四種可執行策略',data:{type:'tows_strategy',title:'專題執行策略｜TOWS 範例',so:['運用程式能力製作競賽原型'],st:['利用教師指導提早確認資料需求'],wo:['先使用開源資料做小規模驗證'],wt:['保留替代題目並限制第一版範圍']}},
{id:'scqa_framework',label:'SCQA 報告敘事',desc:'情境、衝突、問題、答案',data:{type:'scqa_framework',title:'作業改善提案｜SCQA 範例',situation:'目前工作站以人工尋找零件。',complication:'產品種類增加，尋料時間與錯料風險升高。',question:'如何在有限預算內降低尋料浪費？',answer:'試行定點備料與視覺標示，再比較改善前後數據。'}}
];window.VC_LEARNING_TEMPLATES.push(...all);CHARTS.push(...all.map(t=>[t.id,t.label]));const base=chartConfig;
chartConfig=function(d){if(!all.some(t=>t.id===d?.type))return base(d);if(typeof d.title!=='string'||!d.title.trim())throw Error('需要 title。');const E=s=>safeText(String(s)),wrap=s=>{const a=Array.from(s),rows=[];while(a.length)rows.push(E(a.splice(0,24).join('')));return rows.join('<br>');},text=k=>{if(typeof d[k]!=='string'||!d[k].trim()||d[k].length>500)throw Error(k+' 使用 1–500 字文字。');return wrap(d[k]);},list=k=>{if(!Array.isArray(d[k])||!d[k].length||d[k].length>8||d[k].some(s=>typeof s!=='string'||!s.trim()||s.length>120))throw Error(k+' 使用 1–8 個項目，每項最多 120 字。');return d[k].map(s=>'• '+wrap(s)).join('<br>');};let headers,values;
if(d.type==='prep_framework'){headers=['表達階段','報告內容'];values=[['P｜觀點','R｜理由','E｜例子／證據','P｜重申與行動'],['point','reason','example','restatement'].map(text)];}
else if(d.type==='scqa_framework'){headers=['敘事階段','報告內容'];values=[['S｜情境','C｜衝突','Q｜問題','A｜答案'],['situation','complication','question','answer'].map(text)];}
else if(d.type==='swot_analysis'){headers=['因素來源','正向因素','負向因素'];values=[['內部','外部'],['<b>S｜優勢</b><br>'+list('strengths'),'<b>O｜機會</b><br>'+list('opportunities')],['<b>W｜弱勢</b><br>'+list('weaknesses'),'<b>T｜威脅</b><br>'+list('threats')]];}
else{headers=['資源與限制','O｜運用機會','T｜應對威脅'];values=[['S｜運用優勢','W｜改善弱勢'],['<b>SO</b><br>'+list('so'),'<b>WO</b><br>'+list('wo')],['<b>ST</b><br>'+list('st'),'<b>WT</b><br>'+list('wt')]];}
const rows=values[0].map((_,i)=>Math.max(...values.map(col=>String(col[i]).split('<br>').length))),height=rows.map(n=>Math.max(74,n*24+28));return {traces:[{type:'table',columnwidth:values.length===2?[1,3]:[1,2.4,2.4],header:{values:headers,height:42,align:'left',font:{size:15}},cells:{values,height:Math.max(...height),align:'left',font:{size:14}}}],layout:{title:{text:E(d.title)},margin:{t:90,l:35,r:35,b:35}}};};})();
